export enum MetadataToken {
  PUBLIC_METADATA_TOKEN = 'PUBLIC_METADATA_TOKEN',
  EMIT_METADATA_TOKEN = 'EMIT_METADATA_TOKEN',
  SCOPE_METADATA_TOKEN = 'SCOPE_METADATA_TOKEN',
  ADMIN_ONLY_METADATA_TOKEN = 'ADMIN_ONLY_METADATA_TOKEN',
  RESOURCE_NAME_METADATA_TOKEN = 'RESOURCE_NAME_METADATA_TOKEN',
  OPERATION_NAME_METADATA_TOKEN = 'OPERATION_NAME_METADATA_TOKEN',

  PERMISSIONS_METADATA_TOKEN = 'PERMISSIONS_METADATA_TOKEN',
  ROLES_METADATA_TOKEN = 'ROLES_METADATA_TOKEN',
  PROFILES_METADATA_TOKEN = 'PROFILES_METADATA_TOKEN',

  STRICT_RATE_LIMIT = 'STRICT_RATE_LIMIT',
}
