import type { DMMF } from '@prisma/generator-helper';

export function printControllerClass(model: DMMF.Model) {
    return [
        `import { Inject } from '@nestjs/common';`,
        `import { Controller, type ResourceOperations } from '@vnodes/nest';`,
        `import { ${model.name}CreateDto, ${model.name}QueryDto, ${model.name}ReadDto, ${model.name}UpdateDto } from './dtos/index.js';`,
        `import { ${model.name}Service } from './tag.service.js';`,
        ``,
        `@Controller({`,
        `    createDto: ${model.name}CreateDto,`,
        `    updateDto: ${model.name}UpdateDto,`,
        `    queryDto: ${model.name}QueryDto,`,
        `    readDto: ${model.name}ReadDto,`,
        `})`,
        `export class ${model.name}Controller implements ResourceOperations {`,
        `    constructor(@Inject(${model.name}Service) protected readonly service: ${model.name}Service) {}`,
        ``,
        `    find(query: ${model.name}QueryDto) {`,
        `        return this.service.find(query);`,
        `    }`,
        ``,
        `    findById(id: number) {`,
        `        return this.service.findByIdOrThrow(id);`,
        `    }`,
        ``,
        `    create(data: ${model.name}CreateDto) {`,
        `        return this.service.create(data);`,
        `    }`,
        ``,
        `    update(id: number, data: Partial<unknown>): unknown {`,
        `        return this.service.update(id, data);`,
        `    }`,
        ``,
        `    delete(id: number): unknown {`,
        `        return this.service.softDelete(id);`,
        `    }`,
        `}`,
    ].join('\n');
}
