import { Profile } from './profile.js';

export const EnvDefault = {
  APP_ID: 'sample',
  PROFILE: Profile.DEV,
  PORT: 3000,
  PREFIX: 'api',
  DESC: 'sample service',
  DB_NAME: 'vnodes',
  DB_SCHEMA: 'sample',
  DB_USERNAME: 'vnodes',
  DB_PASSWORD: 'password',
  DB_HOST: 'localhost',
  DB_PORT: 5432,
  DB_URL: 'postgres://vnodes:password@localhost:5432/vnodes?schema=sample',
  DB_MIGRATIONS_PATH: 'prisma/migrations',
  DB_PRISMA_SCHEMA_PATH: 'prisma/schema.prisma',
  ROOT_USERNAME: 'root',
  ROOT_PASSWORD: '!Password123.',
  JWT_SECRET: 'dev_secret',
  CACHE_TTL: 7_000,
  THROTTLER_TTL: 60_000,
  THROTTLER_LIMIT: 100,
  DB_POOL_MAX: 20,
  DB_POOL_CONNECTION_TIMEOUT_MILLIS: 60_000,
  DB_POOL_IDLE_TIMEOUT_MILLIS: 60_000,
  DB_POOL_MAX_USES: 7_500,
  DB_POOL_STATEMENT_TIMEOUT: 1_000,
  DB_POOL_QUERY_TIMEOUT: 1_000,
  DB_POOL_LOCK_TIMEOUT: 1_000,
} as const;
