// @index(['./**/*.ts', '!./**/*.spec.ts', '!./**/{main,serve,index}.ts', '!./**/prisma'], f => `export * from '${f.path}.js'`)
export * from './app.module.js';
export * from './resources/address/address.controller.js';
export * from './resources/address/address.dto.js';
export * from './resources/address/address.module.js';
export * from './resources/address/address.service.js';
export * from './resources/contact/contact.controller.js';
export * from './resources/contact/contact.dto.js';
export * from './resources/contact/contact.module.js';
export * from './resources/contact/contact.service.js';
export * from './resources/email/email.controller.js';
export * from './resources/email/email.dto.js';
export * from './resources/email/email.module.js';
export * from './resources/email/email.service.js';
export * from './resources/phone/phone.controller.js';
export * from './resources/phone/phone.dto.js';
export * from './resources/phone/phone.module.js';
export * from './resources/phone/phone.service.js';
export * from './resources/resource.module.js';
