packages:
  - apps/*
  - plugins/*
  - libs/*
  - dbs/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - prisma
  - unrs-resolver
