export enum Env {
    DOCS_PATH = 'DOCS_PATH',
    API_PREFIX = 'API_PREFIX',
    APP_ID = 'APP_ID',
    APP_DESCRIPTION = 'APP_DESCRIPTION',
    PORT = 'PORT',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
    THROTTLE_TTL = 'THROTTLE_TTL',
    THROTTLE_LIMIT = 'THROTTLE_LIMIT',
    CACHE_TTL = 'CACHE_TTL',
    TRUST_PROXY = 'TRUST_PROXY',
    DISABLE_CORS = 'DISABLE_CORS',
}
