/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Gender = {
    Male: 'Male',
    Female: 'Female',
} as const;

export type Gender = (typeof Gender)[keyof typeof Gender];

export const ContactType = {
    Personal: 'Personal',
    Work: 'Work',
} as const;

export type ContactType = (typeof ContactType)[keyof typeof ContactType];
