import type { GeneratorOptions } from '@prisma/generator-helper';

const header = `// This file was generated by a custom prisma generator, do not edit manually.\n`;

export default async function onGenerate(options: GeneratorOptions) {
    console.log(header);
    console.log('Versino', options.version);
    console.log('Generating http-client');
}

// rest of generator code...
