import type { DMMF } from '@prisma/generator-helper';
import { names } from '@vnodes/names';
import { isSearchableField } from '../utils/is-field.js';

export function printServiceClass(model: DMMF.Model) {
  const { pascal, camel, kebab } = names(model.name);
  const includes = '';
  const searchableFields = model.fields
    .filter(isSearchableField)
    .map((e) => `'${e.name}'`)
    .join(',');

  return [
    `import { Injectable } from '@vnodes/nest';`,
    `import { InjectDelegate } from '@vnodes/prisma';`,
    `import { Prisma as P } from '../../prisma/client.js';`,
    `import type { ${pascal}QueryDto, ${pascal}CreateDto, ${pascal}UpdateDto } from './${kebab}.dto.js';`,
    ``,
    ``,
    `@Injectable()`,
    `export class ${pascal}Service {`,
    `  protected readonly searchableFields: P.${pascal}ScalarFieldEnum[] = [${searchableFields} ];`,
    ``,
    `  constructor(@InjectDelegate(P.ModelName.${pascal}) protected readonly ${camel}Delegate: P.${pascal}Delegate) {}`,
    ``,
    `  protected toPaginationArgs(query: ${pascal}QueryDto): P.${pascal}FindManyArgs {`,
    `    return {`,
    `      take: query.take ?? 20,`,
    `      skip: query.skip ?? 0,`,
    `    };`,
    `  }`,
    ``,
    `  protected toOrderByArgs(query: ${pascal}QueryDto): P.${pascal}FindManyArgs | undefined {`,
    `    return {`,
    `      orderBy: { [query.orderBy ?? 'id']: query.orderDir ?? 'asc' },`,
    `    };`,
    `  }`,
    ``,
    `  protected toWhereArgs(query: ${pascal}QueryDto): P.${pascal}FindManyArgs | undefined {`,
    `    const where: P.${pascal}FindManyArgs['where'] = {`,
    `      OR: [],`,
    `    };`,
    ``,
    `    if (query.withDeleted !== true) {`,
    `      where.deletedAt = { equals: null };`,
    `    }`,
    ``,
    `    if (query.search) {`,
    `      where.OR = this.searchableFields.map((e) => {`,
    `        return { [e]: { contains: query.search, mode: 'insensitive' } };`,
    `      });`,
    `    }`,
    ``,
    `    return undefined;`,
    `  }`,
    ``,
    `  protected toFindManyArgs(query: ${pascal}QueryDto): P.${pascal}FindManyArgs {`,
    `    return {`,
    `      ...this.toWhereArgs(query),`,
    `      ...this.toOrderByArgs(query),`,
    `      ...this.toPaginationArgs(query),`,
    `      distinct: query.distinct ?? 'id',`,
    `    };`,
    `  }`,
    ``,
    `  findMany(query: ${pascal}QueryDto) {`,
    `    return this.${camel}Delegate.findMany({`,
    `      ...this.toFindManyArgs(query),`,
    `      ${includes},`,
    `    });`,
    `  }`,
    ``,
    `  findOneById(id: number) {`,
    `    return this.${camel}Delegate.findUnique({`,
    `      where: { id },`,
    `      ${includes},`,
    `    });`,
    `  }`,
    ``,
    `  deleteOneById(id: number) {`,
    `    return this.${camel}Delegate.delete({ where: { id }, select: { id: true } });`,
    `  }`,
    ``,
    `  softDeleteOneById(id: number) {`,
    `    return this.${camel}Delegate.update({ where: { id }, data: { deletedAt: new Date() }, select:{ id:true } });`,
    `  }`,
    ``,
    `  recoverOneById(id: number) {`,
    `    return this.${camel}Delegate.update({ where: { id }, data: { deletedAt: null } });`,
    `  }`,
    `}`,
  ].join('\n');
}
