export enum Env {
    PORT = 'PORT',
    THROTTLE_TTL = 'THROTTLE_TTL',
    THROTTLE_LIMIT = 'THROTTLE_LIMIT',
    CACHE_TTL = 'CACHE_TTL',
    TRUST_PROXY = 'TRUST_PROXY',
    DISABLE_CORS = 'DISABLE_CORS',
}
