/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `AccessTokenPermission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model AccessTokenPermission
 *
 */
export type AccessTokenPermissionModel = runtime.Types.Result.DefaultSelection<Prisma.$AccessTokenPermissionPayload>;

export type AggregateAccessTokenPermission = {
    _count: AccessTokenPermissionCountAggregateOutputType | null;
    _avg: AccessTokenPermissionAvgAggregateOutputType | null;
    _sum: AccessTokenPermissionSumAggregateOutputType | null;
    _min: AccessTokenPermissionMinAggregateOutputType | null;
    _max: AccessTokenPermissionMaxAggregateOutputType | null;
};

export type AccessTokenPermissionAvgAggregateOutputType = {
    id: number | null;
    accessTokenId: number | null;
    permissionId: number | null;
};

export type AccessTokenPermissionSumAggregateOutputType = {
    id: number | null;
    accessTokenId: number | null;
    permissionId: number | null;
};

export type AccessTokenPermissionMinAggregateOutputType = {
    id: number | null;
    createdAt: Date | null;
    updatedAt: Date | null;
    deletedAt: Date | null;
    accessTokenId: number | null;
    permissionId: number | null;
};

export type AccessTokenPermissionMaxAggregateOutputType = {
    id: number | null;
    createdAt: Date | null;
    updatedAt: Date | null;
    deletedAt: Date | null;
    accessTokenId: number | null;
    permissionId: number | null;
};

export type AccessTokenPermissionCountAggregateOutputType = {
    id: number;
    createdAt: number;
    updatedAt: number;
    deletedAt: number;
    accessTokenId: number;
    permissionId: number;
    _all: number;
};

export type AccessTokenPermissionAvgAggregateInputType = {
    id?: true;
    accessTokenId?: true;
    permissionId?: true;
};

export type AccessTokenPermissionSumAggregateInputType = {
    id?: true;
    accessTokenId?: true;
    permissionId?: true;
};

export type AccessTokenPermissionMinAggregateInputType = {
    id?: true;
    createdAt?: true;
    updatedAt?: true;
    deletedAt?: true;
    accessTokenId?: true;
    permissionId?: true;
};

export type AccessTokenPermissionMaxAggregateInputType = {
    id?: true;
    createdAt?: true;
    updatedAt?: true;
    deletedAt?: true;
    accessTokenId?: true;
    permissionId?: true;
};

export type AccessTokenPermissionCountAggregateInputType = {
    id?: true;
    createdAt?: true;
    updatedAt?: true;
    deletedAt?: true;
    accessTokenId?: true;
    permissionId?: true;
    _all?: true;
};

export type AccessTokenPermissionAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which AccessTokenPermission to aggregate.
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AccessTokenPermissions to fetch.
     */
    orderBy?:
        | Prisma.AccessTokenPermissionOrderByWithRelationInput
        | Prisma.AccessTokenPermissionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.AccessTokenPermissionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AccessTokenPermissions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AccessTokenPermissions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned AccessTokenPermissions
     **/
    _count?: true | AccessTokenPermissionCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: AccessTokenPermissionAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: AccessTokenPermissionSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: AccessTokenPermissionMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: AccessTokenPermissionMaxAggregateInputType;
};

export type GetAccessTokenPermissionAggregateType<T extends AccessTokenPermissionAggregateArgs> = {
    [P in keyof T & keyof AggregateAccessTokenPermission]: P extends '_count' | 'count'
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateAccessTokenPermission[P]>
        : Prisma.GetScalarType<T[P], AggregateAccessTokenPermission[P]>;
};

export type AccessTokenPermissionGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.AccessTokenPermissionWhereInput;
    orderBy?:
        | Prisma.AccessTokenPermissionOrderByWithAggregationInput
        | Prisma.AccessTokenPermissionOrderByWithAggregationInput[];
    by: Prisma.AccessTokenPermissionScalarFieldEnum[] | Prisma.AccessTokenPermissionScalarFieldEnum;
    having?: Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: AccessTokenPermissionCountAggregateInputType | true;
    _avg?: AccessTokenPermissionAvgAggregateInputType;
    _sum?: AccessTokenPermissionSumAggregateInputType;
    _min?: AccessTokenPermissionMinAggregateInputType;
    _max?: AccessTokenPermissionMaxAggregateInputType;
};

export type AccessTokenPermissionGroupByOutputType = {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    deletedAt: Date | null;
    accessTokenId: number;
    permissionId: number;
    _count: AccessTokenPermissionCountAggregateOutputType | null;
    _avg: AccessTokenPermissionAvgAggregateOutputType | null;
    _sum: AccessTokenPermissionSumAggregateOutputType | null;
    _min: AccessTokenPermissionMinAggregateOutputType | null;
    _max: AccessTokenPermissionMaxAggregateOutputType | null;
};

type GetAccessTokenPermissionGroupByPayload<T extends AccessTokenPermissionGroupByArgs> = Prisma.PrismaPromise<
    Array<
        Prisma.PickEnumerable<AccessTokenPermissionGroupByOutputType, T['by']> & {
            [P in keyof T & keyof AccessTokenPermissionGroupByOutputType]: P extends '_count'
                ? T[P] extends boolean
                    ? number
                    : Prisma.GetScalarType<T[P], AccessTokenPermissionGroupByOutputType[P]>
                : Prisma.GetScalarType<T[P], AccessTokenPermissionGroupByOutputType[P]>;
        }
    >
>;

export type AccessTokenPermissionWhereInput = {
    AND?: Prisma.AccessTokenPermissionWhereInput | Prisma.AccessTokenPermissionWhereInput[];
    OR?: Prisma.AccessTokenPermissionWhereInput[];
    NOT?: Prisma.AccessTokenPermissionWhereInput | Prisma.AccessTokenPermissionWhereInput[];
    id?: Prisma.IntFilter<'AccessTokenPermission'> | number;
    createdAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
    deletedAt?: Prisma.DateTimeNullableFilter<'AccessTokenPermission'> | Date | string | null;
    accessTokenId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
    permissionId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
    accessToken?: Prisma.XOR<Prisma.AccessTokenScalarRelationFilter, Prisma.AccessTokenWhereInput>;
    permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>;
};

export type AccessTokenPermissionOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
    accessToken?: Prisma.AccessTokenOrderByWithRelationInput;
    permission?: Prisma.PermissionOrderByWithRelationInput;
};

export type AccessTokenPermissionWhereUniqueInput = Prisma.AtLeast<
    {
        id?: number;
        AND?: Prisma.AccessTokenPermissionWhereInput | Prisma.AccessTokenPermissionWhereInput[];
        OR?: Prisma.AccessTokenPermissionWhereInput[];
        NOT?: Prisma.AccessTokenPermissionWhereInput | Prisma.AccessTokenPermissionWhereInput[];
        createdAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
        deletedAt?: Prisma.DateTimeNullableFilter<'AccessTokenPermission'> | Date | string | null;
        accessTokenId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
        permissionId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
        accessToken?: Prisma.XOR<Prisma.AccessTokenScalarRelationFilter, Prisma.AccessTokenWhereInput>;
        permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>;
    },
    'id'
>;

export type AccessTokenPermissionOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
    _count?: Prisma.AccessTokenPermissionCountOrderByAggregateInput;
    _avg?: Prisma.AccessTokenPermissionAvgOrderByAggregateInput;
    _max?: Prisma.AccessTokenPermissionMaxOrderByAggregateInput;
    _min?: Prisma.AccessTokenPermissionMinOrderByAggregateInput;
    _sum?: Prisma.AccessTokenPermissionSumOrderByAggregateInput;
};

export type AccessTokenPermissionScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput
        | Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput[];
    OR?: Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput
        | Prisma.AccessTokenPermissionScalarWhereWithAggregatesInput[];
    id?: Prisma.IntWithAggregatesFilter<'AccessTokenPermission'> | number;
    createdAt?: Prisma.DateTimeWithAggregatesFilter<'AccessTokenPermission'> | Date | string;
    updatedAt?: Prisma.DateTimeWithAggregatesFilter<'AccessTokenPermission'> | Date | string;
    deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<'AccessTokenPermission'> | Date | string | null;
    accessTokenId?: Prisma.IntWithAggregatesFilter<'AccessTokenPermission'> | number;
    permissionId?: Prisma.IntWithAggregatesFilter<'AccessTokenPermission'> | number;
};

export type AccessTokenPermissionCreateInput = {
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessToken: Prisma.AccessTokenCreateNestedOneWithoutAccessTokenPermissionsInput;
    permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput;
};

export type AccessTokenPermissionUncheckedCreateInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessTokenId: number;
    permissionId: number;
};

export type AccessTokenPermissionUpdateInput = {
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessToken?: Prisma.AccessTokenUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput;
    permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput;
};

export type AccessTokenPermissionUncheckedUpdateInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number;
    permissionId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionCreateManyInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessTokenId: number;
    permissionId: number;
};

export type AccessTokenPermissionUpdateManyMutationInput = {
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type AccessTokenPermissionUncheckedUpdateManyInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number;
    permissionId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionListRelationFilter = {
    every?: Prisma.AccessTokenPermissionWhereInput;
    some?: Prisma.AccessTokenPermissionWhereInput;
    none?: Prisma.AccessTokenPermissionWhereInput;
};

export type AccessTokenPermissionOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type AccessTokenPermissionCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    deletedAt?: Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
};

export type AccessTokenPermissionAvgOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
};

export type AccessTokenPermissionMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    deletedAt?: Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
};

export type AccessTokenPermissionMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    deletedAt?: Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
};

export type AccessTokenPermissionSumOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    accessTokenId?: Prisma.SortOrder;
    permissionId?: Prisma.SortOrder;
};

export type AccessTokenPermissionCreateNestedManyWithoutPermissionInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutPermissionInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyPermissionInputEnvelope;
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
};

export type AccessTokenPermissionUncheckedCreateNestedManyWithoutPermissionInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutPermissionInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyPermissionInputEnvelope;
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
};

export type AccessTokenPermissionUpdateManyWithoutPermissionNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutPermissionInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput[];
    upsert?:
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutPermissionInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyPermissionInputEnvelope;
    set?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    disconnect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    delete?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    update?:
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutPermissionInput[];
    updateMany?:
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutPermissionInput[];
    deleteMany?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
};

export type AccessTokenPermissionUncheckedUpdateManyWithoutPermissionNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutPermissionInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutPermissionInput[];
    upsert?:
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutPermissionInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyPermissionInputEnvelope;
    set?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    disconnect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    delete?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    update?:
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutPermissionInput[];
    updateMany?:
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutPermissionInput
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutPermissionInput[];
    deleteMany?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
};

export type AccessTokenPermissionCreateNestedManyWithoutAccessTokenInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyAccessTokenInputEnvelope;
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
};

export type AccessTokenPermissionUncheckedCreateNestedManyWithoutAccessTokenInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyAccessTokenInputEnvelope;
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
};

export type AccessTokenPermissionUpdateManyWithoutAccessTokenNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput[];
    upsert?:
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutAccessTokenInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyAccessTokenInputEnvelope;
    set?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    disconnect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    delete?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    update?:
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutAccessTokenInput[];
    updateMany?:
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutAccessTokenInput[];
    deleteMany?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
};

export type AccessTokenPermissionUncheckedUpdateManyWithoutAccessTokenNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
              Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
          >
        | Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput[]
        | Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput[];
    connectOrCreate?:
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput[];
    upsert?:
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpsertWithWhereUniqueWithoutAccessTokenInput[];
    createMany?: Prisma.AccessTokenPermissionCreateManyAccessTokenInputEnvelope;
    set?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    disconnect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    delete?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    connect?: Prisma.AccessTokenPermissionWhereUniqueInput | Prisma.AccessTokenPermissionWhereUniqueInput[];
    update?:
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpdateWithWhereUniqueWithoutAccessTokenInput[];
    updateMany?:
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutAccessTokenInput
        | Prisma.AccessTokenPermissionUpdateManyWithWhereWithoutAccessTokenInput[];
    deleteMany?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
};

export type AccessTokenPermissionCreateWithoutPermissionInput = {
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessToken: Prisma.AccessTokenCreateNestedOneWithoutAccessTokenPermissionsInput;
};

export type AccessTokenPermissionUncheckedCreateWithoutPermissionInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessTokenId: number;
};

export type AccessTokenPermissionCreateOrConnectWithoutPermissionInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
        Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
    >;
};

export type AccessTokenPermissionCreateManyPermissionInputEnvelope = {
    data:
        | Prisma.AccessTokenPermissionCreateManyPermissionInput
        | Prisma.AccessTokenPermissionCreateManyPermissionInput[];
    skipDuplicates?: boolean;
};

export type AccessTokenPermissionUpsertWithWhereUniqueWithoutPermissionInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateWithoutPermissionInput,
        Prisma.AccessTokenPermissionUncheckedUpdateWithoutPermissionInput
    >;
    create: Prisma.XOR<
        Prisma.AccessTokenPermissionCreateWithoutPermissionInput,
        Prisma.AccessTokenPermissionUncheckedCreateWithoutPermissionInput
    >;
};

export type AccessTokenPermissionUpdateWithWhereUniqueWithoutPermissionInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateWithoutPermissionInput,
        Prisma.AccessTokenPermissionUncheckedUpdateWithoutPermissionInput
    >;
};

export type AccessTokenPermissionUpdateManyWithWhereWithoutPermissionInput = {
    where: Prisma.AccessTokenPermissionScalarWhereInput;
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateManyMutationInput,
        Prisma.AccessTokenPermissionUncheckedUpdateManyWithoutPermissionInput
    >;
};

export type AccessTokenPermissionScalarWhereInput = {
    AND?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
    OR?: Prisma.AccessTokenPermissionScalarWhereInput[];
    NOT?: Prisma.AccessTokenPermissionScalarWhereInput | Prisma.AccessTokenPermissionScalarWhereInput[];
    id?: Prisma.IntFilter<'AccessTokenPermission'> | number;
    createdAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'AccessTokenPermission'> | Date | string;
    deletedAt?: Prisma.DateTimeNullableFilter<'AccessTokenPermission'> | Date | string | null;
    accessTokenId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
    permissionId?: Prisma.IntFilter<'AccessTokenPermission'> | number;
};

export type AccessTokenPermissionCreateWithoutAccessTokenInput = {
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput;
};

export type AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    permissionId: number;
};

export type AccessTokenPermissionCreateOrConnectWithoutAccessTokenInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
        Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
    >;
};

export type AccessTokenPermissionCreateManyAccessTokenInputEnvelope = {
    data:
        | Prisma.AccessTokenPermissionCreateManyAccessTokenInput
        | Prisma.AccessTokenPermissionCreateManyAccessTokenInput[];
    skipDuplicates?: boolean;
};

export type AccessTokenPermissionUpsertWithWhereUniqueWithoutAccessTokenInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateWithoutAccessTokenInput,
        Prisma.AccessTokenPermissionUncheckedUpdateWithoutAccessTokenInput
    >;
    create: Prisma.XOR<
        Prisma.AccessTokenPermissionCreateWithoutAccessTokenInput,
        Prisma.AccessTokenPermissionUncheckedCreateWithoutAccessTokenInput
    >;
};

export type AccessTokenPermissionUpdateWithWhereUniqueWithoutAccessTokenInput = {
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateWithoutAccessTokenInput,
        Prisma.AccessTokenPermissionUncheckedUpdateWithoutAccessTokenInput
    >;
};

export type AccessTokenPermissionUpdateManyWithWhereWithoutAccessTokenInput = {
    where: Prisma.AccessTokenPermissionScalarWhereInput;
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateManyMutationInput,
        Prisma.AccessTokenPermissionUncheckedUpdateManyWithoutAccessTokenInput
    >;
};

export type AccessTokenPermissionCreateManyPermissionInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    accessTokenId: number;
};

export type AccessTokenPermissionUpdateWithoutPermissionInput = {
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessToken?: Prisma.AccessTokenUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput;
};

export type AccessTokenPermissionUncheckedUpdateWithoutPermissionInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionUncheckedUpdateManyWithoutPermissionInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionCreateManyAccessTokenInput = {
    id?: number;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    deletedAt?: Date | string | null;
    permissionId: number;
};

export type AccessTokenPermissionUpdateWithoutAccessTokenInput = {
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput;
};

export type AccessTokenPermissionUncheckedUpdateWithoutAccessTokenInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    permissionId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionUncheckedUpdateManyWithoutAccessTokenInput = {
    id?: Prisma.IntFieldUpdateOperationsInput | number;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
    permissionId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type AccessTokenPermissionSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        deletedAt?: boolean;
        accessTokenId?: boolean;
        permissionId?: boolean;
        accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
        permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['accessTokenPermission']
>;

export type AccessTokenPermissionSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        deletedAt?: boolean;
        accessTokenId?: boolean;
        permissionId?: boolean;
        accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
        permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['accessTokenPermission']
>;

export type AccessTokenPermissionSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        deletedAt?: boolean;
        accessTokenId?: boolean;
        permissionId?: boolean;
        accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
        permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['accessTokenPermission']
>;

export type AccessTokenPermissionSelectScalar = {
    id?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    deletedAt?: boolean;
    accessTokenId?: boolean;
    permissionId?: boolean;
};

export type AccessTokenPermissionOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    'id' | 'createdAt' | 'updatedAt' | 'deletedAt' | 'accessTokenId' | 'permissionId',
    ExtArgs['result']['accessTokenPermission']
>;
export type AccessTokenPermissionInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
    permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
};
export type AccessTokenPermissionIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
    permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
};
export type AccessTokenPermissionIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>;
    permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>;
};

export type $AccessTokenPermissionPayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    name: 'AccessTokenPermission';
    objects: {
        accessToken: Prisma.$AccessTokenPayload<ExtArgs>;
        permission: Prisma.$PermissionPayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: number;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            accessTokenId: number;
            permissionId: number;
        },
        ExtArgs['result']['accessTokenPermission']
    >;
    composites: {};
};

export type AccessTokenPermissionGetPayload<S extends boolean | null | undefined | AccessTokenPermissionDefaultArgs> =
    runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload, S>;

export type AccessTokenPermissionCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<AccessTokenPermissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccessTokenPermissionCountAggregateInputType | true;
};

export interface AccessTokenPermissionDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>['model']['AccessTokenPermission'];
        meta: { name: 'AccessTokenPermission' };
    };
    /**
     * Find zero or one AccessTokenPermission that matches the filter.
     * @param {AccessTokenPermissionFindUniqueArgs} args - Arguments to find a AccessTokenPermission
     * @example
     * // Get one AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends AccessTokenPermissionFindUniqueArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'findUnique',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one AccessTokenPermission that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {AccessTokenPermissionFindUniqueOrThrowArgs} args - Arguments to find a AccessTokenPermission
     * @example
     * // Get one AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends AccessTokenPermissionFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'findUniqueOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first AccessTokenPermission that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionFindFirstArgs} args - Arguments to find a AccessTokenPermission
     * @example
     * // Get one AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends AccessTokenPermissionFindFirstArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'findFirst',
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first AccessTokenPermission that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionFindFirstOrThrowArgs} args - Arguments to find a AccessTokenPermission
     * @example
     * // Get one AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends AccessTokenPermissionFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'findFirstOrThrow',
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more AccessTokenPermissions that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all AccessTokenPermissions
     * const accessTokenPermissions = await prisma.accessTokenPermission.findMany()
     *
     * // Get first 10 AccessTokenPermissions
     * const accessTokenPermissions = await prisma.accessTokenPermission.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const accessTokenPermissionWithIdOnly = await prisma.accessTokenPermission.findMany({ select: { id: true } })
     *
     */
    findMany<T extends AccessTokenPermissionFindManyArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
    >;

    /**
     * Create a AccessTokenPermission.
     * @param {AccessTokenPermissionCreateArgs} args - Arguments to create a AccessTokenPermission.
     * @example
     * // Create one AccessTokenPermission
     * const AccessTokenPermission = await prisma.accessTokenPermission.create({
     *   data: {
     *     // ... data to create a AccessTokenPermission
     *   }
     * })
     *
     */
    create<T extends AccessTokenPermissionCreateArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many AccessTokenPermissions.
     * @param {AccessTokenPermissionCreateManyArgs} args - Arguments to create many AccessTokenPermissions.
     * @example
     * // Create many AccessTokenPermissions
     * const accessTokenPermission = await prisma.accessTokenPermission.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends AccessTokenPermissionCreateManyArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many AccessTokenPermissions and returns the data saved in the database.
     * @param {AccessTokenPermissionCreateManyAndReturnArgs} args - Arguments to create many AccessTokenPermissions.
     * @example
     * // Create many AccessTokenPermissions
     * const accessTokenPermission = await prisma.accessTokenPermission.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many AccessTokenPermissions and only return the `id`
     * const accessTokenPermissionWithIdOnly = await prisma.accessTokenPermission.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends AccessTokenPermissionCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'createManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a AccessTokenPermission.
     * @param {AccessTokenPermissionDeleteArgs} args - Arguments to delete one AccessTokenPermission.
     * @example
     * // Delete one AccessTokenPermission
     * const AccessTokenPermission = await prisma.accessTokenPermission.delete({
     *   where: {
     *     // ... filter to delete one AccessTokenPermission
     *   }
     * })
     *
     */
    delete<T extends AccessTokenPermissionDeleteArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one AccessTokenPermission.
     * @param {AccessTokenPermissionUpdateArgs} args - Arguments to update one AccessTokenPermission.
     * @example
     * // Update one AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends AccessTokenPermissionUpdateArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more AccessTokenPermissions.
     * @param {AccessTokenPermissionDeleteManyArgs} args - Arguments to filter AccessTokenPermissions to delete.
     * @example
     * // Delete a few AccessTokenPermissions
     * const { count } = await prisma.accessTokenPermission.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends AccessTokenPermissionDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, AccessTokenPermissionDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more AccessTokenPermissions.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many AccessTokenPermissions
     * const accessTokenPermission = await prisma.accessTokenPermission.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends AccessTokenPermissionUpdateManyArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more AccessTokenPermissions and returns the data updated in the database.
     * @param {AccessTokenPermissionUpdateManyAndReturnArgs} args - Arguments to update many AccessTokenPermissions.
     * @example
     * // Update many AccessTokenPermissions
     * const accessTokenPermission = await prisma.accessTokenPermission.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more AccessTokenPermissions and only return the `id`
     * const accessTokenPermissionWithIdOnly = await prisma.accessTokenPermission.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends AccessTokenPermissionUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$AccessTokenPermissionPayload<ExtArgs>,
            T,
            'updateManyAndReturn',
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one AccessTokenPermission.
     * @param {AccessTokenPermissionUpsertArgs} args - Arguments to update or create a AccessTokenPermission.
     * @example
     * // Update or create a AccessTokenPermission
     * const accessTokenPermission = await prisma.accessTokenPermission.upsert({
     *   create: {
     *     // ... data to create a AccessTokenPermission
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the AccessTokenPermission we want to update
     *   }
     * })
     */
    upsert<T extends AccessTokenPermissionUpsertArgs>(
        args: Prisma.SelectSubset<T, AccessTokenPermissionUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenPermissionClient<
        runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of AccessTokenPermissions.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionCountArgs} args - Arguments to filter AccessTokenPermissions to count.
     * @example
     * // Count the number of AccessTokenPermissions
     * const count = await prisma.accessTokenPermission.count({
     *   where: {
     *     // ... the filter for the AccessTokenPermissions we want to count
     *   }
     * })
     **/
    count<T extends AccessTokenPermissionCountArgs>(
        args?: Prisma.Subset<T, AccessTokenPermissionCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
            ? T['select'] extends true
                ? number
                : Prisma.GetScalarType<T['select'], AccessTokenPermissionCountAggregateOutputType>
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a AccessTokenPermission.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends AccessTokenPermissionAggregateArgs>(
        args: Prisma.Subset<T, AccessTokenPermissionAggregateArgs>,
    ): Prisma.PrismaPromise<GetAccessTokenPermissionAggregateType<T>>;

    /**
     * Group by AccessTokenPermission.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {AccessTokenPermissionGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends AccessTokenPermissionGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<'skip', Prisma.Keys<T>>,
            Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: AccessTokenPermissionGroupByArgs['orderBy'] }
            : { orderBy?: AccessTokenPermissionGroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
                }[HavingFields]
              : 'take' extends Prisma.Keys<T>
                ? 'orderBy' extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : 'skip' extends Prisma.Keys<T>
                  ? 'orderBy' extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, AccessTokenPermissionGroupByArgs, OrderByArg> & InputErrors,
    ): {} extends InputErrors ? GetAccessTokenPermissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the AccessTokenPermission model
     */
    readonly fields: AccessTokenPermissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccessTokenPermission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccessTokenPermissionClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: 'PrismaPromise';
    accessToken<T extends Prisma.AccessTokenDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.AccessTokenDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__AccessTokenClient<
        | runtime.Types.Result.GetResult<Prisma.$AccessTokenPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    permission<T extends Prisma.PermissionDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.PermissionDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__PermissionClient<
        | runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the AccessTokenPermission model
 */
export interface AccessTokenPermissionFieldRefs {
    readonly id: Prisma.FieldRef<'AccessTokenPermission', 'Int'>;
    readonly createdAt: Prisma.FieldRef<'AccessTokenPermission', 'DateTime'>;
    readonly updatedAt: Prisma.FieldRef<'AccessTokenPermission', 'DateTime'>;
    readonly deletedAt: Prisma.FieldRef<'AccessTokenPermission', 'DateTime'>;
    readonly accessTokenId: Prisma.FieldRef<'AccessTokenPermission', 'Int'>;
    readonly permissionId: Prisma.FieldRef<'AccessTokenPermission', 'Int'>;
}

// Custom InputTypes
/**
 * AccessTokenPermission findUnique
 */
export type AccessTokenPermissionFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter, which AccessTokenPermission to fetch.
     */
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
};

/**
 * AccessTokenPermission findUniqueOrThrow
 */
export type AccessTokenPermissionFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter, which AccessTokenPermission to fetch.
     */
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
};

/**
 * AccessTokenPermission findFirst
 */
export type AccessTokenPermissionFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter, which AccessTokenPermission to fetch.
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AccessTokenPermissions to fetch.
     */
    orderBy?:
        | Prisma.AccessTokenPermissionOrderByWithRelationInput
        | Prisma.AccessTokenPermissionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for AccessTokenPermissions.
     */
    cursor?: Prisma.AccessTokenPermissionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AccessTokenPermissions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AccessTokenPermissions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of AccessTokenPermissions.
     */
    distinct?: Prisma.AccessTokenPermissionScalarFieldEnum | Prisma.AccessTokenPermissionScalarFieldEnum[];
};

/**
 * AccessTokenPermission findFirstOrThrow
 */
export type AccessTokenPermissionFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter, which AccessTokenPermission to fetch.
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AccessTokenPermissions to fetch.
     */
    orderBy?:
        | Prisma.AccessTokenPermissionOrderByWithRelationInput
        | Prisma.AccessTokenPermissionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for AccessTokenPermissions.
     */
    cursor?: Prisma.AccessTokenPermissionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AccessTokenPermissions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AccessTokenPermissions.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of AccessTokenPermissions.
     */
    distinct?: Prisma.AccessTokenPermissionScalarFieldEnum | Prisma.AccessTokenPermissionScalarFieldEnum[];
};

/**
 * AccessTokenPermission findMany
 */
export type AccessTokenPermissionFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter, which AccessTokenPermissions to fetch.
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of AccessTokenPermissions to fetch.
     */
    orderBy?:
        | Prisma.AccessTokenPermissionOrderByWithRelationInput
        | Prisma.AccessTokenPermissionOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing AccessTokenPermissions.
     */
    cursor?: Prisma.AccessTokenPermissionWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` AccessTokenPermissions from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` AccessTokenPermissions.
     */
    skip?: number;
    distinct?: Prisma.AccessTokenPermissionScalarFieldEnum | Prisma.AccessTokenPermissionScalarFieldEnum[];
};

/**
 * AccessTokenPermission create
 */
export type AccessTokenPermissionCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * The data needed to create a AccessTokenPermission.
     */
    data: Prisma.XOR<Prisma.AccessTokenPermissionCreateInput, Prisma.AccessTokenPermissionUncheckedCreateInput>;
};

/**
 * AccessTokenPermission createMany
 */
export type AccessTokenPermissionCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many AccessTokenPermissions.
     */
    data: Prisma.AccessTokenPermissionCreateManyInput | Prisma.AccessTokenPermissionCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * AccessTokenPermission createManyAndReturn
 */
export type AccessTokenPermissionCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * The data used to create many AccessTokenPermissions.
     */
    data: Prisma.AccessTokenPermissionCreateManyInput | Prisma.AccessTokenPermissionCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * AccessTokenPermission update
 */
export type AccessTokenPermissionUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * The data needed to update a AccessTokenPermission.
     */
    data: Prisma.XOR<Prisma.AccessTokenPermissionUpdateInput, Prisma.AccessTokenPermissionUncheckedUpdateInput>;
    /**
     * Choose, which AccessTokenPermission to update.
     */
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
};

/**
 * AccessTokenPermission updateMany
 */
export type AccessTokenPermissionUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update AccessTokenPermissions.
     */
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateManyMutationInput,
        Prisma.AccessTokenPermissionUncheckedUpdateManyInput
    >;
    /**
     * Filter which AccessTokenPermissions to update
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * Limit how many AccessTokenPermissions to update.
     */
    limit?: number;
};

/**
 * AccessTokenPermission updateManyAndReturn
 */
export type AccessTokenPermissionUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * The data used to update AccessTokenPermissions.
     */
    data: Prisma.XOR<
        Prisma.AccessTokenPermissionUpdateManyMutationInput,
        Prisma.AccessTokenPermissionUncheckedUpdateManyInput
    >;
    /**
     * Filter which AccessTokenPermissions to update
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * Limit how many AccessTokenPermissions to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * AccessTokenPermission upsert
 */
export type AccessTokenPermissionUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * The filter to search for the AccessTokenPermission to update in case it exists.
     */
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
    /**
     * In case the AccessTokenPermission found by the `where` argument doesn't exist, create a new AccessTokenPermission with this data.
     */
    create: Prisma.XOR<Prisma.AccessTokenPermissionCreateInput, Prisma.AccessTokenPermissionUncheckedCreateInput>;
    /**
     * In case the AccessTokenPermission was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.AccessTokenPermissionUpdateInput, Prisma.AccessTokenPermissionUncheckedUpdateInput>;
};

/**
 * AccessTokenPermission delete
 */
export type AccessTokenPermissionDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
    /**
     * Filter which AccessTokenPermission to delete.
     */
    where: Prisma.AccessTokenPermissionWhereUniqueInput;
};

/**
 * AccessTokenPermission deleteMany
 */
export type AccessTokenPermissionDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which AccessTokenPermissions to delete
     */
    where?: Prisma.AccessTokenPermissionWhereInput;
    /**
     * Limit how many AccessTokenPermissions to delete.
     */
    limit?: number;
};

/**
 * AccessTokenPermission without action
 */
export type AccessTokenPermissionDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the AccessTokenPermission
     */
    select?: Prisma.AccessTokenPermissionSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the AccessTokenPermission
     */
    omit?: Prisma.AccessTokenPermissionOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.AccessTokenPermissionInclude<ExtArgs> | null;
};
