
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Manufacturer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Manufacturer
 * 
 */
export type ManufacturerModel = runtime.Types.Result.DefaultSelection<Prisma.$ManufacturerPayload>

export type AggregateManufacturer = {
  _count: ManufacturerCountAggregateOutputType | null
  _avg: ManufacturerAvgAggregateOutputType | null
  _sum: ManufacturerSumAggregateOutputType | null
  _min: ManufacturerMinAggregateOutputType | null
  _max: ManufacturerMaxAggregateOutputType | null
}

export type ManufacturerAvgAggregateOutputType = {
  id: number | null
}

export type ManufacturerSumAggregateOutputType = {
  id: number | null
}

export type ManufacturerMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  name: string | null
}

export type ManufacturerMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  name: string | null
}

export type ManufacturerCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  name: number
  _all: number
}


export type ManufacturerAvgAggregateInputType = {
  id?: true
}

export type ManufacturerSumAggregateInputType = {
  id?: true
}

export type ManufacturerMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
}

export type ManufacturerMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
}

export type ManufacturerCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  name?: true
  _all?: true
}

export type ManufacturerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Manufacturer to aggregate.
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manufacturers to fetch.
   */
  orderBy?: Prisma.ManufacturerOrderByWithRelationInput | Prisma.ManufacturerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManufacturerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manufacturers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manufacturers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Manufacturers
  **/
  _count?: true | ManufacturerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ManufacturerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ManufacturerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManufacturerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManufacturerMaxAggregateInputType
}

export type GetManufacturerAggregateType<T extends ManufacturerAggregateArgs> = {
      [P in keyof T & keyof AggregateManufacturer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManufacturer[P]>
    : Prisma.GetScalarType<T[P], AggregateManufacturer[P]>
}




export type ManufacturerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManufacturerWhereInput
  orderBy?: Prisma.ManufacturerOrderByWithAggregationInput | Prisma.ManufacturerOrderByWithAggregationInput[]
  by: Prisma.ManufacturerScalarFieldEnum[] | Prisma.ManufacturerScalarFieldEnum
  having?: Prisma.ManufacturerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManufacturerCountAggregateInputType | true
  _avg?: ManufacturerAvgAggregateInputType
  _sum?: ManufacturerSumAggregateInputType
  _min?: ManufacturerMinAggregateInputType
  _max?: ManufacturerMaxAggregateInputType
}

export type ManufacturerGroupByOutputType = {
  id: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  name: string
  _count: ManufacturerCountAggregateOutputType | null
  _avg: ManufacturerAvgAggregateOutputType | null
  _sum: ManufacturerSumAggregateOutputType | null
  _min: ManufacturerMinAggregateOutputType | null
  _max: ManufacturerMaxAggregateOutputType | null
}

type GetManufacturerGroupByPayload<T extends ManufacturerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManufacturerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManufacturerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManufacturerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManufacturerGroupByOutputType[P]>
      }
    >
  >



export type ManufacturerWhereInput = {
  AND?: Prisma.ManufacturerWhereInput | Prisma.ManufacturerWhereInput[]
  OR?: Prisma.ManufacturerWhereInput[]
  NOT?: Prisma.ManufacturerWhereInput | Prisma.ManufacturerWhereInput[]
  id?: Prisma.IntFilter<"Manufacturer"> | number
  createdAt?: Prisma.DateTimeFilter<"Manufacturer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Manufacturer"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Manufacturer"> | Date | string | null
  name?: Prisma.StringFilter<"Manufacturer"> | string
}

export type ManufacturerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ManufacturerWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.ManufacturerWhereInput | Prisma.ManufacturerWhereInput[]
  OR?: Prisma.ManufacturerWhereInput[]
  NOT?: Prisma.ManufacturerWhereInput | Prisma.ManufacturerWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Manufacturer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Manufacturer"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Manufacturer"> | Date | string | null
}, "id" | "name">

export type ManufacturerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.ManufacturerCountOrderByAggregateInput
  _avg?: Prisma.ManufacturerAvgOrderByAggregateInput
  _max?: Prisma.ManufacturerMaxOrderByAggregateInput
  _min?: Prisma.ManufacturerMinOrderByAggregateInput
  _sum?: Prisma.ManufacturerSumOrderByAggregateInput
}

export type ManufacturerScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManufacturerScalarWhereWithAggregatesInput | Prisma.ManufacturerScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManufacturerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManufacturerScalarWhereWithAggregatesInput | Prisma.ManufacturerScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Manufacturer"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Manufacturer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Manufacturer"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Manufacturer"> | Date | string | null
  name?: Prisma.StringWithAggregatesFilter<"Manufacturer"> | string
}

export type ManufacturerCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
}

export type ManufacturerUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
}

export type ManufacturerUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManufacturerUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManufacturerCreateManyInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
}

export type ManufacturerUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManufacturerUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManufacturerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ManufacturerAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ManufacturerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ManufacturerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ManufacturerSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type ManufacturerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
}, ExtArgs["result"]["manufacturer"]>

export type ManufacturerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
}, ExtArgs["result"]["manufacturer"]>

export type ManufacturerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
}, ExtArgs["result"]["manufacturer"]>

export type ManufacturerSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  name?: boolean
}

export type ManufacturerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "deletedAt" | "name", ExtArgs["result"]["manufacturer"]>

export type $ManufacturerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Manufacturer"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    name: string
  }, ExtArgs["result"]["manufacturer"]>
  composites: {}
}

export type ManufacturerGetPayload<S extends boolean | null | undefined | ManufacturerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload, S>

export type ManufacturerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManufacturerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManufacturerCountAggregateInputType | true
  }

export interface ManufacturerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Manufacturer'], meta: { name: 'Manufacturer' } }
  /**
   * Find zero or one Manufacturer that matches the filter.
   * @param {ManufacturerFindUniqueArgs} args - Arguments to find a Manufacturer
   * @example
   * // Get one Manufacturer
   * const manufacturer = await prisma.manufacturer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManufacturerFindUniqueArgs>(args: Prisma.SelectSubset<T, ManufacturerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Manufacturer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManufacturerFindUniqueOrThrowArgs} args - Arguments to find a Manufacturer
   * @example
   * // Get one Manufacturer
   * const manufacturer = await prisma.manufacturer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManufacturerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManufacturerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Manufacturer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerFindFirstArgs} args - Arguments to find a Manufacturer
   * @example
   * // Get one Manufacturer
   * const manufacturer = await prisma.manufacturer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManufacturerFindFirstArgs>(args?: Prisma.SelectSubset<T, ManufacturerFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Manufacturer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerFindFirstOrThrowArgs} args - Arguments to find a Manufacturer
   * @example
   * // Get one Manufacturer
   * const manufacturer = await prisma.manufacturer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManufacturerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManufacturerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Manufacturers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Manufacturers
   * const manufacturers = await prisma.manufacturer.findMany()
   * 
   * // Get first 10 Manufacturers
   * const manufacturers = await prisma.manufacturer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const manufacturerWithIdOnly = await prisma.manufacturer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManufacturerFindManyArgs>(args?: Prisma.SelectSubset<T, ManufacturerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Manufacturer.
   * @param {ManufacturerCreateArgs} args - Arguments to create a Manufacturer.
   * @example
   * // Create one Manufacturer
   * const Manufacturer = await prisma.manufacturer.create({
   *   data: {
   *     // ... data to create a Manufacturer
   *   }
   * })
   * 
   */
  create<T extends ManufacturerCreateArgs>(args: Prisma.SelectSubset<T, ManufacturerCreateArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Manufacturers.
   * @param {ManufacturerCreateManyArgs} args - Arguments to create many Manufacturers.
   * @example
   * // Create many Manufacturers
   * const manufacturer = await prisma.manufacturer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManufacturerCreateManyArgs>(args?: Prisma.SelectSubset<T, ManufacturerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Manufacturers and returns the data saved in the database.
   * @param {ManufacturerCreateManyAndReturnArgs} args - Arguments to create many Manufacturers.
   * @example
   * // Create many Manufacturers
   * const manufacturer = await prisma.manufacturer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Manufacturers and only return the `id`
   * const manufacturerWithIdOnly = await prisma.manufacturer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManufacturerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManufacturerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Manufacturer.
   * @param {ManufacturerDeleteArgs} args - Arguments to delete one Manufacturer.
   * @example
   * // Delete one Manufacturer
   * const Manufacturer = await prisma.manufacturer.delete({
   *   where: {
   *     // ... filter to delete one Manufacturer
   *   }
   * })
   * 
   */
  delete<T extends ManufacturerDeleteArgs>(args: Prisma.SelectSubset<T, ManufacturerDeleteArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Manufacturer.
   * @param {ManufacturerUpdateArgs} args - Arguments to update one Manufacturer.
   * @example
   * // Update one Manufacturer
   * const manufacturer = await prisma.manufacturer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManufacturerUpdateArgs>(args: Prisma.SelectSubset<T, ManufacturerUpdateArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Manufacturers.
   * @param {ManufacturerDeleteManyArgs} args - Arguments to filter Manufacturers to delete.
   * @example
   * // Delete a few Manufacturers
   * const { count } = await prisma.manufacturer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManufacturerDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManufacturerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Manufacturers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Manufacturers
   * const manufacturer = await prisma.manufacturer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManufacturerUpdateManyArgs>(args: Prisma.SelectSubset<T, ManufacturerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Manufacturers and returns the data updated in the database.
   * @param {ManufacturerUpdateManyAndReturnArgs} args - Arguments to update many Manufacturers.
   * @example
   * // Update many Manufacturers
   * const manufacturer = await prisma.manufacturer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Manufacturers and only return the `id`
   * const manufacturerWithIdOnly = await prisma.manufacturer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManufacturerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManufacturerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Manufacturer.
   * @param {ManufacturerUpsertArgs} args - Arguments to update or create a Manufacturer.
   * @example
   * // Update or create a Manufacturer
   * const manufacturer = await prisma.manufacturer.upsert({
   *   create: {
   *     // ... data to create a Manufacturer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Manufacturer we want to update
   *   }
   * })
   */
  upsert<T extends ManufacturerUpsertArgs>(args: Prisma.SelectSubset<T, ManufacturerUpsertArgs<ExtArgs>>): Prisma.Prisma__ManufacturerClient<runtime.Types.Result.GetResult<Prisma.$ManufacturerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Manufacturers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerCountArgs} args - Arguments to filter Manufacturers to count.
   * @example
   * // Count the number of Manufacturers
   * const count = await prisma.manufacturer.count({
   *   where: {
   *     // ... the filter for the Manufacturers we want to count
   *   }
   * })
  **/
  count<T extends ManufacturerCountArgs>(
    args?: Prisma.Subset<T, ManufacturerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManufacturerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Manufacturer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManufacturerAggregateArgs>(args: Prisma.Subset<T, ManufacturerAggregateArgs>): Prisma.PrismaPromise<GetManufacturerAggregateType<T>>

  /**
   * Group by Manufacturer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManufacturerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManufacturerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManufacturerGroupByArgs['orderBy'] }
      : { orderBy?: ManufacturerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManufacturerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManufacturerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Manufacturer model
 */
readonly fields: ManufacturerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Manufacturer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManufacturerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Manufacturer model
 */
export interface ManufacturerFieldRefs {
  readonly id: Prisma.FieldRef<"Manufacturer", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Manufacturer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Manufacturer", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Manufacturer", 'DateTime'>
  readonly name: Prisma.FieldRef<"Manufacturer", 'String'>
}
    

// Custom InputTypes
/**
 * Manufacturer findUnique
 */
export type ManufacturerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter, which Manufacturer to fetch.
   */
  where: Prisma.ManufacturerWhereUniqueInput
}

/**
 * Manufacturer findUniqueOrThrow
 */
export type ManufacturerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter, which Manufacturer to fetch.
   */
  where: Prisma.ManufacturerWhereUniqueInput
}

/**
 * Manufacturer findFirst
 */
export type ManufacturerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter, which Manufacturer to fetch.
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manufacturers to fetch.
   */
  orderBy?: Prisma.ManufacturerOrderByWithRelationInput | Prisma.ManufacturerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Manufacturers.
   */
  cursor?: Prisma.ManufacturerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manufacturers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manufacturers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Manufacturers.
   */
  distinct?: Prisma.ManufacturerScalarFieldEnum | Prisma.ManufacturerScalarFieldEnum[]
}

/**
 * Manufacturer findFirstOrThrow
 */
export type ManufacturerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter, which Manufacturer to fetch.
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manufacturers to fetch.
   */
  orderBy?: Prisma.ManufacturerOrderByWithRelationInput | Prisma.ManufacturerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Manufacturers.
   */
  cursor?: Prisma.ManufacturerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manufacturers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manufacturers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Manufacturers.
   */
  distinct?: Prisma.ManufacturerScalarFieldEnum | Prisma.ManufacturerScalarFieldEnum[]
}

/**
 * Manufacturer findMany
 */
export type ManufacturerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter, which Manufacturers to fetch.
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Manufacturers to fetch.
   */
  orderBy?: Prisma.ManufacturerOrderByWithRelationInput | Prisma.ManufacturerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Manufacturers.
   */
  cursor?: Prisma.ManufacturerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Manufacturers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Manufacturers.
   */
  skip?: number
  distinct?: Prisma.ManufacturerScalarFieldEnum | Prisma.ManufacturerScalarFieldEnum[]
}

/**
 * Manufacturer create
 */
export type ManufacturerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * The data needed to create a Manufacturer.
   */
  data: Prisma.XOR<Prisma.ManufacturerCreateInput, Prisma.ManufacturerUncheckedCreateInput>
}

/**
 * Manufacturer createMany
 */
export type ManufacturerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Manufacturers.
   */
  data: Prisma.ManufacturerCreateManyInput | Prisma.ManufacturerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Manufacturer createManyAndReturn
 */
export type ManufacturerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * The data used to create many Manufacturers.
   */
  data: Prisma.ManufacturerCreateManyInput | Prisma.ManufacturerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Manufacturer update
 */
export type ManufacturerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * The data needed to update a Manufacturer.
   */
  data: Prisma.XOR<Prisma.ManufacturerUpdateInput, Prisma.ManufacturerUncheckedUpdateInput>
  /**
   * Choose, which Manufacturer to update.
   */
  where: Prisma.ManufacturerWhereUniqueInput
}

/**
 * Manufacturer updateMany
 */
export type ManufacturerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Manufacturers.
   */
  data: Prisma.XOR<Prisma.ManufacturerUpdateManyMutationInput, Prisma.ManufacturerUncheckedUpdateManyInput>
  /**
   * Filter which Manufacturers to update
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * Limit how many Manufacturers to update.
   */
  limit?: number
}

/**
 * Manufacturer updateManyAndReturn
 */
export type ManufacturerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * The data used to update Manufacturers.
   */
  data: Prisma.XOR<Prisma.ManufacturerUpdateManyMutationInput, Prisma.ManufacturerUncheckedUpdateManyInput>
  /**
   * Filter which Manufacturers to update
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * Limit how many Manufacturers to update.
   */
  limit?: number
}

/**
 * Manufacturer upsert
 */
export type ManufacturerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * The filter to search for the Manufacturer to update in case it exists.
   */
  where: Prisma.ManufacturerWhereUniqueInput
  /**
   * In case the Manufacturer found by the `where` argument doesn't exist, create a new Manufacturer with this data.
   */
  create: Prisma.XOR<Prisma.ManufacturerCreateInput, Prisma.ManufacturerUncheckedCreateInput>
  /**
   * In case the Manufacturer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManufacturerUpdateInput, Prisma.ManufacturerUncheckedUpdateInput>
}

/**
 * Manufacturer delete
 */
export type ManufacturerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
  /**
   * Filter which Manufacturer to delete.
   */
  where: Prisma.ManufacturerWhereUniqueInput
}

/**
 * Manufacturer deleteMany
 */
export type ManufacturerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Manufacturers to delete
   */
  where?: Prisma.ManufacturerWhereInput
  /**
   * Limit how many Manufacturers to delete.
   */
  limit?: number
}

/**
 * Manufacturer without action
 */
export type ManufacturerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Manufacturer
   */
  select?: Prisma.ManufacturerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Manufacturer
   */
  omit?: Prisma.ManufacturerOmit<ExtArgs> | null
}
