export enum EnvKey {
  // Server
  APP_ID = 'APP_ID',
  PROFILE = 'PROFILE',
  PORT = 'PORT',
  PREFIX = 'PREFIX',
  DESC = 'DESC',

  // System
  ROOT_USERNAME = 'ROOT_USERNAME',
  ROOT_PASSWORD = 'ROOT_PASSWORD',

  // Security
  JWT_SECRET = 'JWT_SECRET',
  CACHE_TTL = 'CACHE_TTL',
  THROTTLER_TTL = 'THROTTLER_TTL',
  THROTTLER_LIMIT = 'THROTTLER_LIMIT',

  //   Database
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_URL = 'DB_URL',
  DB_SCHEMA = 'DB_SCHEMA',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_POOL_MAX = 'DB_POOL_MAX',
  DB_POOL_CONNECTION_TIMEOUT_MILLIS = 'DB_POOL_CONNECTION_TIMEOUT_MILLIS',
  DB_POOL_IDLE_TIMEOUT_MILLIS = 'DB_POOL_IDLE_TIMEOUT_MILLIS',
  DB_POOL_MAX_USES = 'DB_POOL_MAX_USES',
  DB_POOL_STATEMENT_TIMEOUT = 'DB_POOL_STATEMENT_TIMEOUT',
  DB_POOL_QUERY_TIMEOUT = 'DB_POOL_QUERY_TIMEOUT',
  DB_POOL_LOCK_TIMEOUT = 'DB_POOL_LOCK_TIMEOUT',
}
