
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Company` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Company
 * 
 */
export type CompanyModel = runtime.Types.Result.DefaultSelection<Prisma.$CompanyPayload>

export type AggregateCompany = {
  _count: CompanyCountAggregateOutputType | null
  _avg: CompanyAvgAggregateOutputType | null
  _sum: CompanySumAggregateOutputType | null
  _min: CompanyMinAggregateOutputType | null
  _max: CompanyMaxAggregateOutputType | null
}

export type CompanyAvgAggregateOutputType = {
  id: number | null
  industryId: number | null
}

export type CompanySumAggregateOutputType = {
  id: number | null
  industryId: number | null
}

export type CompanyMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  industryId: number | null
  name: string | null
}

export type CompanyMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  industryId: number | null
  name: string | null
}

export type CompanyCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  industryId: number
  name: number
  profiles: number
  openTime: number
  _all: number
}


export type CompanyAvgAggregateInputType = {
  id?: true
  industryId?: true
}

export type CompanySumAggregateInputType = {
  id?: true
  industryId?: true
}

export type CompanyMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  industryId?: true
  name?: true
}

export type CompanyMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  industryId?: true
  name?: true
}

export type CompanyCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  industryId?: true
  name?: true
  profiles?: true
  openTime?: true
  _all?: true
}

export type CompanyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Company to aggregate.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Companies
  **/
  _count?: true | CompanyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CompanyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CompanySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CompanyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CompanyMaxAggregateInputType
}

export type GetCompanyAggregateType<T extends CompanyAggregateArgs> = {
      [P in keyof T & keyof AggregateCompany]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompany[P]>
    : Prisma.GetScalarType<T[P], AggregateCompany[P]>
}




export type CompanyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompanyWhereInput
  orderBy?: Prisma.CompanyOrderByWithAggregationInput | Prisma.CompanyOrderByWithAggregationInput[]
  by: Prisma.CompanyScalarFieldEnum[] | Prisma.CompanyScalarFieldEnum
  having?: Prisma.CompanyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CompanyCountAggregateInputType | true
  _avg?: CompanyAvgAggregateInputType
  _sum?: CompanySumAggregateInputType
  _min?: CompanyMinAggregateInputType
  _max?: CompanyMaxAggregateInputType
}

export type CompanyGroupByOutputType = {
  id: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  industryId: number | null
  name: string
  profiles: string[]
  openTime: runtime.JsonValue | null
  _count: CompanyCountAggregateOutputType | null
  _avg: CompanyAvgAggregateOutputType | null
  _sum: CompanySumAggregateOutputType | null
  _min: CompanyMinAggregateOutputType | null
  _max: CompanyMaxAggregateOutputType | null
}

type GetCompanyGroupByPayload<T extends CompanyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CompanyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CompanyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CompanyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CompanyGroupByOutputType[P]>
      }
    >
  >



export type CompanyWhereInput = {
  AND?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  OR?: Prisma.CompanyWhereInput[]
  NOT?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  id?: Prisma.IntFilter<"Company"> | number
  createdAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Company"> | Date | string | null
  industryId?: Prisma.IntNullableFilter<"Company"> | number | null
  name?: Prisma.StringFilter<"Company"> | string
  profiles?: Prisma.StringNullableListFilter<"Company">
  openTime?: Prisma.JsonNullableFilter<"Company">
  industry?: Prisma.XOR<Prisma.IndustryNullableScalarRelationFilter, Prisma.IndustryWhereInput> | null
  contacts?: Prisma.ContactListRelationFilter
  taxInfo?: Prisma.XOR<Prisma.TaxInfoNullableScalarRelationFilter, Prisma.TaxInfoWhereInput> | null
}

export type CompanyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  industryId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  profiles?: Prisma.SortOrder
  openTime?: Prisma.SortOrderInput | Prisma.SortOrder
  industry?: Prisma.IndustryOrderByWithRelationInput
  contacts?: Prisma.ContactOrderByRelationAggregateInput
  taxInfo?: Prisma.TaxInfoOrderByWithRelationInput
}

export type CompanyWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  OR?: Prisma.CompanyWhereInput[]
  NOT?: Prisma.CompanyWhereInput | Prisma.CompanyWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Company"> | Date | string | null
  industryId?: Prisma.IntNullableFilter<"Company"> | number | null
  profiles?: Prisma.StringNullableListFilter<"Company">
  openTime?: Prisma.JsonNullableFilter<"Company">
  industry?: Prisma.XOR<Prisma.IndustryNullableScalarRelationFilter, Prisma.IndustryWhereInput> | null
  contacts?: Prisma.ContactListRelationFilter
  taxInfo?: Prisma.XOR<Prisma.TaxInfoNullableScalarRelationFilter, Prisma.TaxInfoWhereInput> | null
}, "id" | "name">

export type CompanyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  industryId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  profiles?: Prisma.SortOrder
  openTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CompanyCountOrderByAggregateInput
  _avg?: Prisma.CompanyAvgOrderByAggregateInput
  _max?: Prisma.CompanyMaxOrderByAggregateInput
  _min?: Prisma.CompanyMinOrderByAggregateInput
  _sum?: Prisma.CompanySumOrderByAggregateInput
}

export type CompanyScalarWhereWithAggregatesInput = {
  AND?: Prisma.CompanyScalarWhereWithAggregatesInput | Prisma.CompanyScalarWhereWithAggregatesInput[]
  OR?: Prisma.CompanyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CompanyScalarWhereWithAggregatesInput | Prisma.CompanyScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Company"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Company"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Company"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Company"> | Date | string | null
  industryId?: Prisma.IntNullableWithAggregatesFilter<"Company"> | number | null
  name?: Prisma.StringWithAggregatesFilter<"Company"> | string
  profiles?: Prisma.StringNullableListFilter<"Company">
  openTime?: Prisma.JsonNullableWithAggregatesFilter<"Company">
}

export type CompanyCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryCreateNestedOneWithoutCompaniesInput
  contacts?: Prisma.ContactCreateNestedManyWithoutCompanyInput
  taxInfo?: Prisma.TaxInfoCreateNestedOneWithoutCompanyInput
}

export type CompanyUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  industryId?: number | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedCreateNestedManyWithoutCompanyInput
  taxInfo?: Prisma.TaxInfoUncheckedCreateNestedOneWithoutCompanyInput
}

export type CompanyUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryUpdateOneWithoutCompaniesNestedInput
  contacts?: Prisma.ContactUpdateManyWithoutCompanyNestedInput
  taxInfo?: Prisma.TaxInfoUpdateOneWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  industryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedUpdateManyWithoutCompanyNestedInput
  taxInfo?: Prisma.TaxInfoUncheckedUpdateOneWithoutCompanyNestedInput
}

export type CompanyCreateManyInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  industryId?: number | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type CompanyUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type CompanyUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  industryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type CompanyListRelationFilter = {
  every?: Prisma.CompanyWhereInput
  some?: Prisma.CompanyWhereInput
  none?: Prisma.CompanyWhereInput
}

export type CompanyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type CompanyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  industryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  profiles?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
}

export type CompanyAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  industryId?: Prisma.SortOrder
}

export type CompanyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  industryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CompanyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  industryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CompanySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  industryId?: Prisma.SortOrder
}

export type CompanyNullableScalarRelationFilter = {
  is?: Prisma.CompanyWhereInput | null
  isNot?: Prisma.CompanyWhereInput | null
}

export type CompanyCreateNestedManyWithoutIndustryInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput> | Prisma.CompanyCreateWithoutIndustryInput[] | Prisma.CompanyUncheckedCreateWithoutIndustryInput[]
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutIndustryInput | Prisma.CompanyCreateOrConnectWithoutIndustryInput[]
  createMany?: Prisma.CompanyCreateManyIndustryInputEnvelope
  connect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
}

export type CompanyUncheckedCreateNestedManyWithoutIndustryInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput> | Prisma.CompanyCreateWithoutIndustryInput[] | Prisma.CompanyUncheckedCreateWithoutIndustryInput[]
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutIndustryInput | Prisma.CompanyCreateOrConnectWithoutIndustryInput[]
  createMany?: Prisma.CompanyCreateManyIndustryInputEnvelope
  connect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
}

export type CompanyUpdateManyWithoutIndustryNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput> | Prisma.CompanyCreateWithoutIndustryInput[] | Prisma.CompanyUncheckedCreateWithoutIndustryInput[]
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutIndustryInput | Prisma.CompanyCreateOrConnectWithoutIndustryInput[]
  upsert?: Prisma.CompanyUpsertWithWhereUniqueWithoutIndustryInput | Prisma.CompanyUpsertWithWhereUniqueWithoutIndustryInput[]
  createMany?: Prisma.CompanyCreateManyIndustryInputEnvelope
  set?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  disconnect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  delete?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  connect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  update?: Prisma.CompanyUpdateWithWhereUniqueWithoutIndustryInput | Prisma.CompanyUpdateWithWhereUniqueWithoutIndustryInput[]
  updateMany?: Prisma.CompanyUpdateManyWithWhereWithoutIndustryInput | Prisma.CompanyUpdateManyWithWhereWithoutIndustryInput[]
  deleteMany?: Prisma.CompanyScalarWhereInput | Prisma.CompanyScalarWhereInput[]
}

export type CompanyUncheckedUpdateManyWithoutIndustryNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput> | Prisma.CompanyCreateWithoutIndustryInput[] | Prisma.CompanyUncheckedCreateWithoutIndustryInput[]
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutIndustryInput | Prisma.CompanyCreateOrConnectWithoutIndustryInput[]
  upsert?: Prisma.CompanyUpsertWithWhereUniqueWithoutIndustryInput | Prisma.CompanyUpsertWithWhereUniqueWithoutIndustryInput[]
  createMany?: Prisma.CompanyCreateManyIndustryInputEnvelope
  set?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  disconnect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  delete?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  connect?: Prisma.CompanyWhereUniqueInput | Prisma.CompanyWhereUniqueInput[]
  update?: Prisma.CompanyUpdateWithWhereUniqueWithoutIndustryInput | Prisma.CompanyUpdateWithWhereUniqueWithoutIndustryInput[]
  updateMany?: Prisma.CompanyUpdateManyWithWhereWithoutIndustryInput | Prisma.CompanyUpdateManyWithWhereWithoutIndustryInput[]
  deleteMany?: Prisma.CompanyScalarWhereInput | Prisma.CompanyScalarWhereInput[]
}

export type CompanyCreateprofilesInput = {
  set: string[]
}

export type CompanyUpdateprofilesInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CompanyCreateNestedOneWithoutTaxInfoInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutTaxInfoInput, Prisma.CompanyUncheckedCreateWithoutTaxInfoInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutTaxInfoInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneWithoutTaxInfoNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutTaxInfoInput, Prisma.CompanyUncheckedCreateWithoutTaxInfoInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutTaxInfoInput
  upsert?: Prisma.CompanyUpsertWithoutTaxInfoInput
  disconnect?: Prisma.CompanyWhereInput | boolean
  delete?: Prisma.CompanyWhereInput | boolean
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutTaxInfoInput, Prisma.CompanyUpdateWithoutTaxInfoInput>, Prisma.CompanyUncheckedUpdateWithoutTaxInfoInput>
}

export type CompanyCreateNestedOneWithoutContactsInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutContactsInput, Prisma.CompanyUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutContactsInput
  connect?: Prisma.CompanyWhereUniqueInput
}

export type CompanyUpdateOneWithoutContactsNestedInput = {
  create?: Prisma.XOR<Prisma.CompanyCreateWithoutContactsInput, Prisma.CompanyUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.CompanyCreateOrConnectWithoutContactsInput
  upsert?: Prisma.CompanyUpsertWithoutContactsInput
  disconnect?: Prisma.CompanyWhereInput | boolean
  delete?: Prisma.CompanyWhereInput | boolean
  connect?: Prisma.CompanyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CompanyUpdateToOneWithWhereWithoutContactsInput, Prisma.CompanyUpdateWithoutContactsInput>, Prisma.CompanyUncheckedUpdateWithoutContactsInput>
}

export type CompanyCreateWithoutIndustryInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactCreateNestedManyWithoutCompanyInput
  taxInfo?: Prisma.TaxInfoCreateNestedOneWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutIndustryInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedCreateNestedManyWithoutCompanyInput
  taxInfo?: Prisma.TaxInfoUncheckedCreateNestedOneWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutIndustryInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput>
}

export type CompanyCreateManyIndustryInputEnvelope = {
  data: Prisma.CompanyCreateManyIndustryInput | Prisma.CompanyCreateManyIndustryInput[]
  skipDuplicates?: boolean
}

export type CompanyUpsertWithWhereUniqueWithoutIndustryInput = {
  where: Prisma.CompanyWhereUniqueInput
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutIndustryInput, Prisma.CompanyUncheckedUpdateWithoutIndustryInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutIndustryInput, Prisma.CompanyUncheckedCreateWithoutIndustryInput>
}

export type CompanyUpdateWithWhereUniqueWithoutIndustryInput = {
  where: Prisma.CompanyWhereUniqueInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutIndustryInput, Prisma.CompanyUncheckedUpdateWithoutIndustryInput>
}

export type CompanyUpdateManyWithWhereWithoutIndustryInput = {
  where: Prisma.CompanyScalarWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateManyMutationInput, Prisma.CompanyUncheckedUpdateManyWithoutIndustryInput>
}

export type CompanyScalarWhereInput = {
  AND?: Prisma.CompanyScalarWhereInput | Prisma.CompanyScalarWhereInput[]
  OR?: Prisma.CompanyScalarWhereInput[]
  NOT?: Prisma.CompanyScalarWhereInput | Prisma.CompanyScalarWhereInput[]
  id?: Prisma.IntFilter<"Company"> | number
  createdAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Company"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Company"> | Date | string | null
  industryId?: Prisma.IntNullableFilter<"Company"> | number | null
  name?: Prisma.StringFilter<"Company"> | string
  profiles?: Prisma.StringNullableListFilter<"Company">
  openTime?: Prisma.JsonNullableFilter<"Company">
}

export type CompanyCreateWithoutTaxInfoInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryCreateNestedOneWithoutCompaniesInput
  contacts?: Prisma.ContactCreateNestedManyWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutTaxInfoInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  industryId?: number | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedCreateNestedManyWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutTaxInfoInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutTaxInfoInput, Prisma.CompanyUncheckedCreateWithoutTaxInfoInput>
}

export type CompanyUpsertWithoutTaxInfoInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutTaxInfoInput, Prisma.CompanyUncheckedUpdateWithoutTaxInfoInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutTaxInfoInput, Prisma.CompanyUncheckedCreateWithoutTaxInfoInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutTaxInfoInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutTaxInfoInput, Prisma.CompanyUncheckedUpdateWithoutTaxInfoInput>
}

export type CompanyUpdateWithoutTaxInfoInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryUpdateOneWithoutCompaniesNestedInput
  contacts?: Prisma.ContactUpdateManyWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutTaxInfoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  industryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedUpdateManyWithoutCompanyNestedInput
}

export type CompanyCreateWithoutContactsInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryCreateNestedOneWithoutCompaniesInput
  taxInfo?: Prisma.TaxInfoCreateNestedOneWithoutCompanyInput
}

export type CompanyUncheckedCreateWithoutContactsInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  industryId?: number | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  taxInfo?: Prisma.TaxInfoUncheckedCreateNestedOneWithoutCompanyInput
}

export type CompanyCreateOrConnectWithoutContactsInput = {
  where: Prisma.CompanyWhereUniqueInput
  create: Prisma.XOR<Prisma.CompanyCreateWithoutContactsInput, Prisma.CompanyUncheckedCreateWithoutContactsInput>
}

export type CompanyUpsertWithoutContactsInput = {
  update: Prisma.XOR<Prisma.CompanyUpdateWithoutContactsInput, Prisma.CompanyUncheckedUpdateWithoutContactsInput>
  create: Prisma.XOR<Prisma.CompanyCreateWithoutContactsInput, Prisma.CompanyUncheckedCreateWithoutContactsInput>
  where?: Prisma.CompanyWhereInput
}

export type CompanyUpdateToOneWithWhereWithoutContactsInput = {
  where?: Prisma.CompanyWhereInput
  data: Prisma.XOR<Prisma.CompanyUpdateWithoutContactsInput, Prisma.CompanyUncheckedUpdateWithoutContactsInput>
}

export type CompanyUpdateWithoutContactsInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  industry?: Prisma.IndustryUpdateOneWithoutCompaniesNestedInput
  taxInfo?: Prisma.TaxInfoUpdateOneWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutContactsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  industryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  taxInfo?: Prisma.TaxInfoUncheckedUpdateOneWithoutCompanyNestedInput
}

export type CompanyCreateManyIndustryInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  name: string
  profiles?: Prisma.CompanyCreateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type CompanyUpdateWithoutIndustryInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUpdateManyWithoutCompanyNestedInput
  taxInfo?: Prisma.TaxInfoUpdateOneWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateWithoutIndustryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedUpdateManyWithoutCompanyNestedInput
  taxInfo?: Prisma.TaxInfoUncheckedUpdateOneWithoutCompanyNestedInput
}

export type CompanyUncheckedUpdateManyWithoutIndustryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  profiles?: Prisma.CompanyUpdateprofilesInput | string[]
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type CompanyCountOutputType
 */

export type CompanyCountOutputType = {
  contacts: number
}

export type CompanyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contacts?: boolean | CompanyCountOutputTypeCountContactsArgs
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompanyCountOutputType
   */
  select?: Prisma.CompanyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CompanyCountOutputType without action
 */
export type CompanyCountOutputTypeCountContactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactWhereInput
}


export type CompanySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  industryId?: boolean
  name?: boolean
  profiles?: boolean
  openTime?: boolean
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
  contacts?: boolean | Prisma.Company$contactsArgs<ExtArgs>
  taxInfo?: boolean | Prisma.Company$taxInfoArgs<ExtArgs>
  _count?: boolean | Prisma.CompanyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["company"]>

export type CompanySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  industryId?: boolean
  name?: boolean
  profiles?: boolean
  openTime?: boolean
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
}, ExtArgs["result"]["company"]>

export type CompanySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  industryId?: boolean
  name?: boolean
  profiles?: boolean
  openTime?: boolean
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
}, ExtArgs["result"]["company"]>

export type CompanySelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  industryId?: boolean
  name?: boolean
  profiles?: boolean
  openTime?: boolean
}

export type CompanyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "deletedAt" | "industryId" | "name" | "profiles" | "openTime", ExtArgs["result"]["company"]>
export type CompanyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
  contacts?: boolean | Prisma.Company$contactsArgs<ExtArgs>
  taxInfo?: boolean | Prisma.Company$taxInfoArgs<ExtArgs>
  _count?: boolean | Prisma.CompanyCountOutputTypeDefaultArgs<ExtArgs>
}
export type CompanyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
}
export type CompanyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  industry?: boolean | Prisma.Company$industryArgs<ExtArgs>
}

export type $CompanyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Company"
  objects: {
    industry: Prisma.$IndustryPayload<ExtArgs> | null
    contacts: Prisma.$ContactPayload<ExtArgs>[]
    taxInfo: Prisma.$TaxInfoPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    industryId: number | null
    name: string
    profiles: string[]
    openTime: runtime.JsonValue | null
  }, ExtArgs["result"]["company"]>
  composites: {}
}

export type CompanyGetPayload<S extends boolean | null | undefined | CompanyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CompanyPayload, S>

export type CompanyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CompanyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CompanyCountAggregateInputType | true
  }

export interface CompanyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Company'], meta: { name: 'Company' } }
  /**
   * Find zero or one Company that matches the filter.
   * @param {CompanyFindUniqueArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CompanyFindUniqueArgs>(args: Prisma.SelectSubset<T, CompanyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Company that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CompanyFindUniqueOrThrowArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CompanyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CompanyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindFirstArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CompanyFindFirstArgs>(args?: Prisma.SelectSubset<T, CompanyFindFirstArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Company that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindFirstOrThrowArgs} args - Arguments to find a Company
   * @example
   * // Get one Company
   * const company = await prisma.company.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CompanyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CompanyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Companies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Companies
   * const companies = await prisma.company.findMany()
   * 
   * // Get first 10 Companies
   * const companies = await prisma.company.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const companyWithIdOnly = await prisma.company.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CompanyFindManyArgs>(args?: Prisma.SelectSubset<T, CompanyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Company.
   * @param {CompanyCreateArgs} args - Arguments to create a Company.
   * @example
   * // Create one Company
   * const Company = await prisma.company.create({
   *   data: {
   *     // ... data to create a Company
   *   }
   * })
   * 
   */
  create<T extends CompanyCreateArgs>(args: Prisma.SelectSubset<T, CompanyCreateArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Companies.
   * @param {CompanyCreateManyArgs} args - Arguments to create many Companies.
   * @example
   * // Create many Companies
   * const company = await prisma.company.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CompanyCreateManyArgs>(args?: Prisma.SelectSubset<T, CompanyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Companies and returns the data saved in the database.
   * @param {CompanyCreateManyAndReturnArgs} args - Arguments to create many Companies.
   * @example
   * // Create many Companies
   * const company = await prisma.company.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Companies and only return the `id`
   * const companyWithIdOnly = await prisma.company.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CompanyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CompanyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Company.
   * @param {CompanyDeleteArgs} args - Arguments to delete one Company.
   * @example
   * // Delete one Company
   * const Company = await prisma.company.delete({
   *   where: {
   *     // ... filter to delete one Company
   *   }
   * })
   * 
   */
  delete<T extends CompanyDeleteArgs>(args: Prisma.SelectSubset<T, CompanyDeleteArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Company.
   * @param {CompanyUpdateArgs} args - Arguments to update one Company.
   * @example
   * // Update one Company
   * const company = await prisma.company.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CompanyUpdateArgs>(args: Prisma.SelectSubset<T, CompanyUpdateArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Companies.
   * @param {CompanyDeleteManyArgs} args - Arguments to filter Companies to delete.
   * @example
   * // Delete a few Companies
   * const { count } = await prisma.company.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CompanyDeleteManyArgs>(args?: Prisma.SelectSubset<T, CompanyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Companies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Companies
   * const company = await prisma.company.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CompanyUpdateManyArgs>(args: Prisma.SelectSubset<T, CompanyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Companies and returns the data updated in the database.
   * @param {CompanyUpdateManyAndReturnArgs} args - Arguments to update many Companies.
   * @example
   * // Update many Companies
   * const company = await prisma.company.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Companies and only return the `id`
   * const companyWithIdOnly = await prisma.company.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CompanyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CompanyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Company.
   * @param {CompanyUpsertArgs} args - Arguments to update or create a Company.
   * @example
   * // Update or create a Company
   * const company = await prisma.company.upsert({
   *   create: {
   *     // ... data to create a Company
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Company we want to update
   *   }
   * })
   */
  upsert<T extends CompanyUpsertArgs>(args: Prisma.SelectSubset<T, CompanyUpsertArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Companies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyCountArgs} args - Arguments to filter Companies to count.
   * @example
   * // Count the number of Companies
   * const count = await prisma.company.count({
   *   where: {
   *     // ... the filter for the Companies we want to count
   *   }
   * })
  **/
  count<T extends CompanyCountArgs>(
    args?: Prisma.Subset<T, CompanyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CompanyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Company.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CompanyAggregateArgs>(args: Prisma.Subset<T, CompanyAggregateArgs>): Prisma.PrismaPromise<GetCompanyAggregateType<T>>

  /**
   * Group by Company.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompanyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CompanyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CompanyGroupByArgs['orderBy'] }
      : { orderBy?: CompanyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CompanyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompanyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Company model
 */
readonly fields: CompanyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Company.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CompanyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  industry<T extends Prisma.Company$industryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$industryArgs<ExtArgs>>): Prisma.Prisma__IndustryClient<runtime.Types.Result.GetResult<Prisma.$IndustryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  contacts<T extends Prisma.Company$contactsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$contactsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  taxInfo<T extends Prisma.Company$taxInfoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Company$taxInfoArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Company model
 */
export interface CompanyFieldRefs {
  readonly id: Prisma.FieldRef<"Company", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Company", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Company", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Company", 'DateTime'>
  readonly industryId: Prisma.FieldRef<"Company", 'Int'>
  readonly name: Prisma.FieldRef<"Company", 'String'>
  readonly profiles: Prisma.FieldRef<"Company", 'String[]'>
  readonly openTime: Prisma.FieldRef<"Company", 'Json'>
}
    

// Custom InputTypes
/**
 * Company findUnique
 */
export type CompanyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company findUniqueOrThrow
 */
export type CompanyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company findFirst
 */
export type CompanyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Companies.
   */
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company findFirstOrThrow
 */
export type CompanyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Company to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Companies.
   */
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company findMany
 */
export type CompanyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter, which Companies to fetch.
   */
  where?: Prisma.CompanyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Companies to fetch.
   */
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Companies.
   */
  cursor?: Prisma.CompanyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Companies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Companies.
   */
  skip?: number
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * Company create
 */
export type CompanyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The data needed to create a Company.
   */
  data: Prisma.XOR<Prisma.CompanyCreateInput, Prisma.CompanyUncheckedCreateInput>
}

/**
 * Company createMany
 */
export type CompanyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Companies.
   */
  data: Prisma.CompanyCreateManyInput | Prisma.CompanyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Company createManyAndReturn
 */
export type CompanyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * The data used to create many Companies.
   */
  data: Prisma.CompanyCreateManyInput | Prisma.CompanyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Company update
 */
export type CompanyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The data needed to update a Company.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateInput, Prisma.CompanyUncheckedUpdateInput>
  /**
   * Choose, which Company to update.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company updateMany
 */
export type CompanyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Companies.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateManyMutationInput, Prisma.CompanyUncheckedUpdateManyInput>
  /**
   * Filter which Companies to update
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to update.
   */
  limit?: number
}

/**
 * Company updateManyAndReturn
 */
export type CompanyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * The data used to update Companies.
   */
  data: Prisma.XOR<Prisma.CompanyUpdateManyMutationInput, Prisma.CompanyUncheckedUpdateManyInput>
  /**
   * Filter which Companies to update
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Company upsert
 */
export type CompanyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * The filter to search for the Company to update in case it exists.
   */
  where: Prisma.CompanyWhereUniqueInput
  /**
   * In case the Company found by the `where` argument doesn't exist, create a new Company with this data.
   */
  create: Prisma.XOR<Prisma.CompanyCreateInput, Prisma.CompanyUncheckedCreateInput>
  /**
   * In case the Company was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CompanyUpdateInput, Prisma.CompanyUncheckedUpdateInput>
}

/**
 * Company delete
 */
export type CompanyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  /**
   * Filter which Company to delete.
   */
  where: Prisma.CompanyWhereUniqueInput
}

/**
 * Company deleteMany
 */
export type CompanyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Companies to delete
   */
  where?: Prisma.CompanyWhereInput
  /**
   * Limit how many Companies to delete.
   */
  limit?: number
}

/**
 * Company.industry
 */
export type Company$industryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Industry
   */
  select?: Prisma.IndustrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Industry
   */
  omit?: Prisma.IndustryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IndustryInclude<ExtArgs> | null
  where?: Prisma.IndustryWhereInput
}

/**
 * Company.contacts
 */
export type Company$contactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  where?: Prisma.ContactWhereInput
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  cursor?: Prisma.ContactWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ContactScalarFieldEnum | Prisma.ContactScalarFieldEnum[]
}

/**
 * Company.taxInfo
 */
export type Company$taxInfoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  where?: Prisma.TaxInfoWhereInput
}

/**
 * Company without action
 */
export type CompanyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
}
