
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaxInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TaxInfo
 * 
 */
export type TaxInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$TaxInfoPayload>

export type AggregateTaxInfo = {
  _count: TaxInfoCountAggregateOutputType | null
  _avg: TaxInfoAvgAggregateOutputType | null
  _sum: TaxInfoSumAggregateOutputType | null
  _min: TaxInfoMinAggregateOutputType | null
  _max: TaxInfoMaxAggregateOutputType | null
}

export type TaxInfoAvgAggregateOutputType = {
  id: number | null
  companyId: number | null
  contactId: number | null
}

export type TaxInfoSumAggregateOutputType = {
  id: number | null
  companyId: number | null
  contactId: number | null
}

export type TaxInfoMinAggregateOutputType = {
  id: number | null
  updatedAt: Date | null
  taxNumber: string | null
  taxCountry: string | null
  isTaxExempt: boolean | null
  exemptionNote: string | null
  companyId: number | null
  contactId: number | null
}

export type TaxInfoMaxAggregateOutputType = {
  id: number | null
  updatedAt: Date | null
  taxNumber: string | null
  taxCountry: string | null
  isTaxExempt: boolean | null
  exemptionNote: string | null
  companyId: number | null
  contactId: number | null
}

export type TaxInfoCountAggregateOutputType = {
  id: number
  updatedAt: number
  taxNumber: number
  taxCountry: number
  isTaxExempt: number
  exemptionNote: number
  companyId: number
  contactId: number
  _all: number
}


export type TaxInfoAvgAggregateInputType = {
  id?: true
  companyId?: true
  contactId?: true
}

export type TaxInfoSumAggregateInputType = {
  id?: true
  companyId?: true
  contactId?: true
}

export type TaxInfoMinAggregateInputType = {
  id?: true
  updatedAt?: true
  taxNumber?: true
  taxCountry?: true
  isTaxExempt?: true
  exemptionNote?: true
  companyId?: true
  contactId?: true
}

export type TaxInfoMaxAggregateInputType = {
  id?: true
  updatedAt?: true
  taxNumber?: true
  taxCountry?: true
  isTaxExempt?: true
  exemptionNote?: true
  companyId?: true
  contactId?: true
}

export type TaxInfoCountAggregateInputType = {
  id?: true
  updatedAt?: true
  taxNumber?: true
  taxCountry?: true
  isTaxExempt?: true
  exemptionNote?: true
  companyId?: true
  contactId?: true
  _all?: true
}

export type TaxInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxInfo to aggregate.
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxInfos to fetch.
   */
  orderBy?: Prisma.TaxInfoOrderByWithRelationInput | Prisma.TaxInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaxInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaxInfos
  **/
  _count?: true | TaxInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TaxInfoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TaxInfoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaxInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaxInfoMaxAggregateInputType
}

export type GetTaxInfoAggregateType<T extends TaxInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateTaxInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaxInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateTaxInfo[P]>
}




export type TaxInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaxInfoWhereInput
  orderBy?: Prisma.TaxInfoOrderByWithAggregationInput | Prisma.TaxInfoOrderByWithAggregationInput[]
  by: Prisma.TaxInfoScalarFieldEnum[] | Prisma.TaxInfoScalarFieldEnum
  having?: Prisma.TaxInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaxInfoCountAggregateInputType | true
  _avg?: TaxInfoAvgAggregateInputType
  _sum?: TaxInfoSumAggregateInputType
  _min?: TaxInfoMinAggregateInputType
  _max?: TaxInfoMaxAggregateInputType
}

export type TaxInfoGroupByOutputType = {
  id: number
  updatedAt: Date
  taxNumber: string
  taxCountry: string
  isTaxExempt: boolean
  exemptionNote: string | null
  companyId: number | null
  contactId: number | null
  _count: TaxInfoCountAggregateOutputType | null
  _avg: TaxInfoAvgAggregateOutputType | null
  _sum: TaxInfoSumAggregateOutputType | null
  _min: TaxInfoMinAggregateOutputType | null
  _max: TaxInfoMaxAggregateOutputType | null
}

type GetTaxInfoGroupByPayload<T extends TaxInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaxInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaxInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaxInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaxInfoGroupByOutputType[P]>
      }
    >
  >



export type TaxInfoWhereInput = {
  AND?: Prisma.TaxInfoWhereInput | Prisma.TaxInfoWhereInput[]
  OR?: Prisma.TaxInfoWhereInput[]
  NOT?: Prisma.TaxInfoWhereInput | Prisma.TaxInfoWhereInput[]
  id?: Prisma.IntFilter<"TaxInfo"> | number
  updatedAt?: Prisma.DateTimeFilter<"TaxInfo"> | Date | string
  taxNumber?: Prisma.StringFilter<"TaxInfo"> | string
  taxCountry?: Prisma.StringFilter<"TaxInfo"> | string
  isTaxExempt?: Prisma.BoolFilter<"TaxInfo"> | boolean
  exemptionNote?: Prisma.StringNullableFilter<"TaxInfo"> | string | null
  companyId?: Prisma.IntNullableFilter<"TaxInfo"> | number | null
  contactId?: Prisma.IntNullableFilter<"TaxInfo"> | number | null
  company?: Prisma.XOR<Prisma.CompanyNullableScalarRelationFilter, Prisma.CompanyWhereInput> | null
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}

export type TaxInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxNumber?: Prisma.SortOrder
  taxCountry?: Prisma.SortOrder
  isTaxExempt?: Prisma.SortOrder
  exemptionNote?: Prisma.SortOrderInput | Prisma.SortOrder
  companyId?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  company?: Prisma.CompanyOrderByWithRelationInput
  contact?: Prisma.ContactOrderByWithRelationInput
}

export type TaxInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  taxNumber?: string
  companyId?: number
  contactId?: number
  AND?: Prisma.TaxInfoWhereInput | Prisma.TaxInfoWhereInput[]
  OR?: Prisma.TaxInfoWhereInput[]
  NOT?: Prisma.TaxInfoWhereInput | Prisma.TaxInfoWhereInput[]
  updatedAt?: Prisma.DateTimeFilter<"TaxInfo"> | Date | string
  taxCountry?: Prisma.StringFilter<"TaxInfo"> | string
  isTaxExempt?: Prisma.BoolFilter<"TaxInfo"> | boolean
  exemptionNote?: Prisma.StringNullableFilter<"TaxInfo"> | string | null
  company?: Prisma.XOR<Prisma.CompanyNullableScalarRelationFilter, Prisma.CompanyWhereInput> | null
  contact?: Prisma.XOR<Prisma.ContactNullableScalarRelationFilter, Prisma.ContactWhereInput> | null
}, "id" | "taxNumber" | "companyId" | "contactId">

export type TaxInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxNumber?: Prisma.SortOrder
  taxCountry?: Prisma.SortOrder
  isTaxExempt?: Prisma.SortOrder
  exemptionNote?: Prisma.SortOrderInput | Prisma.SortOrder
  companyId?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TaxInfoCountOrderByAggregateInput
  _avg?: Prisma.TaxInfoAvgOrderByAggregateInput
  _max?: Prisma.TaxInfoMaxOrderByAggregateInput
  _min?: Prisma.TaxInfoMinOrderByAggregateInput
  _sum?: Prisma.TaxInfoSumOrderByAggregateInput
}

export type TaxInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaxInfoScalarWhereWithAggregatesInput | Prisma.TaxInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaxInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaxInfoScalarWhereWithAggregatesInput | Prisma.TaxInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TaxInfo"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TaxInfo"> | Date | string
  taxNumber?: Prisma.StringWithAggregatesFilter<"TaxInfo"> | string
  taxCountry?: Prisma.StringWithAggregatesFilter<"TaxInfo"> | string
  isTaxExempt?: Prisma.BoolWithAggregatesFilter<"TaxInfo"> | boolean
  exemptionNote?: Prisma.StringNullableWithAggregatesFilter<"TaxInfo"> | string | null
  companyId?: Prisma.IntNullableWithAggregatesFilter<"TaxInfo"> | number | null
  contactId?: Prisma.IntNullableWithAggregatesFilter<"TaxInfo"> | number | null
}

export type TaxInfoCreateInput = {
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  company?: Prisma.CompanyCreateNestedOneWithoutTaxInfoInput
  contact?: Prisma.ContactCreateNestedOneWithoutTaxInfoInput
}

export type TaxInfoUncheckedCreateInput = {
  id?: number
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  companyId?: number | null
  contactId?: number | null
}

export type TaxInfoUpdateInput = {
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company?: Prisma.CompanyUpdateOneWithoutTaxInfoNestedInput
  contact?: Prisma.ContactUpdateOneWithoutTaxInfoNestedInput
}

export type TaxInfoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  contactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type TaxInfoCreateManyInput = {
  id?: number
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  companyId?: number | null
  contactId?: number | null
}

export type TaxInfoUpdateManyMutationInput = {
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TaxInfoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  contactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type TaxInfoNullableScalarRelationFilter = {
  is?: Prisma.TaxInfoWhereInput | null
  isNot?: Prisma.TaxInfoWhereInput | null
}

export type TaxInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxNumber?: Prisma.SortOrder
  taxCountry?: Prisma.SortOrder
  isTaxExempt?: Prisma.SortOrder
  exemptionNote?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type TaxInfoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type TaxInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxNumber?: Prisma.SortOrder
  taxCountry?: Prisma.SortOrder
  isTaxExempt?: Prisma.SortOrder
  exemptionNote?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type TaxInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  taxNumber?: Prisma.SortOrder
  taxCountry?: Prisma.SortOrder
  isTaxExempt?: Prisma.SortOrder
  exemptionNote?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type TaxInfoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type TaxInfoCreateNestedOneWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutCompanyInput
  connect?: Prisma.TaxInfoWhereUniqueInput
}

export type TaxInfoUncheckedCreateNestedOneWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutCompanyInput
  connect?: Prisma.TaxInfoWhereUniqueInput
}

export type TaxInfoUpdateOneWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutCompanyInput
  upsert?: Prisma.TaxInfoUpsertWithoutCompanyInput
  disconnect?: Prisma.TaxInfoWhereInput | boolean
  delete?: Prisma.TaxInfoWhereInput | boolean
  connect?: Prisma.TaxInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaxInfoUpdateToOneWithWhereWithoutCompanyInput, Prisma.TaxInfoUpdateWithoutCompanyInput>, Prisma.TaxInfoUncheckedUpdateWithoutCompanyInput>
}

export type TaxInfoUncheckedUpdateOneWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutCompanyInput
  upsert?: Prisma.TaxInfoUpsertWithoutCompanyInput
  disconnect?: Prisma.TaxInfoWhereInput | boolean
  delete?: Prisma.TaxInfoWhereInput | boolean
  connect?: Prisma.TaxInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaxInfoUpdateToOneWithWhereWithoutCompanyInput, Prisma.TaxInfoUpdateWithoutCompanyInput>, Prisma.TaxInfoUncheckedUpdateWithoutCompanyInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TaxInfoCreateNestedOneWithoutContactInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutContactInput
  connect?: Prisma.TaxInfoWhereUniqueInput
}

export type TaxInfoUncheckedCreateNestedOneWithoutContactInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutContactInput
  connect?: Prisma.TaxInfoWhereUniqueInput
}

export type TaxInfoUpdateOneWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutContactInput
  upsert?: Prisma.TaxInfoUpsertWithoutContactInput
  disconnect?: Prisma.TaxInfoWhereInput | boolean
  delete?: Prisma.TaxInfoWhereInput | boolean
  connect?: Prisma.TaxInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaxInfoUpdateToOneWithWhereWithoutContactInput, Prisma.TaxInfoUpdateWithoutContactInput>, Prisma.TaxInfoUncheckedUpdateWithoutContactInput>
}

export type TaxInfoUncheckedUpdateOneWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
  connectOrCreate?: Prisma.TaxInfoCreateOrConnectWithoutContactInput
  upsert?: Prisma.TaxInfoUpsertWithoutContactInput
  disconnect?: Prisma.TaxInfoWhereInput | boolean
  delete?: Prisma.TaxInfoWhereInput | boolean
  connect?: Prisma.TaxInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaxInfoUpdateToOneWithWhereWithoutContactInput, Prisma.TaxInfoUpdateWithoutContactInput>, Prisma.TaxInfoUncheckedUpdateWithoutContactInput>
}

export type TaxInfoCreateWithoutCompanyInput = {
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  contact?: Prisma.ContactCreateNestedOneWithoutTaxInfoInput
}

export type TaxInfoUncheckedCreateWithoutCompanyInput = {
  id?: number
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  contactId?: number | null
}

export type TaxInfoCreateOrConnectWithoutCompanyInput = {
  where: Prisma.TaxInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
}

export type TaxInfoUpsertWithoutCompanyInput = {
  update: Prisma.XOR<Prisma.TaxInfoUpdateWithoutCompanyInput, Prisma.TaxInfoUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.TaxInfoCreateWithoutCompanyInput, Prisma.TaxInfoUncheckedCreateWithoutCompanyInput>
  where?: Prisma.TaxInfoWhereInput
}

export type TaxInfoUpdateToOneWithWhereWithoutCompanyInput = {
  where?: Prisma.TaxInfoWhereInput
  data: Prisma.XOR<Prisma.TaxInfoUpdateWithoutCompanyInput, Prisma.TaxInfoUncheckedUpdateWithoutCompanyInput>
}

export type TaxInfoUpdateWithoutCompanyInput = {
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contact?: Prisma.ContactUpdateOneWithoutTaxInfoNestedInput
}

export type TaxInfoUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type TaxInfoCreateWithoutContactInput = {
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  company?: Prisma.CompanyCreateNestedOneWithoutTaxInfoInput
}

export type TaxInfoUncheckedCreateWithoutContactInput = {
  id?: number
  updatedAt?: Date | string
  taxNumber: string
  taxCountry: string
  isTaxExempt?: boolean
  exemptionNote?: string | null
  companyId?: number | null
}

export type TaxInfoCreateOrConnectWithoutContactInput = {
  where: Prisma.TaxInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
}

export type TaxInfoUpsertWithoutContactInput = {
  update: Prisma.XOR<Prisma.TaxInfoUpdateWithoutContactInput, Prisma.TaxInfoUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.TaxInfoCreateWithoutContactInput, Prisma.TaxInfoUncheckedCreateWithoutContactInput>
  where?: Prisma.TaxInfoWhereInput
}

export type TaxInfoUpdateToOneWithWhereWithoutContactInput = {
  where?: Prisma.TaxInfoWhereInput
  data: Prisma.XOR<Prisma.TaxInfoUpdateWithoutContactInput, Prisma.TaxInfoUncheckedUpdateWithoutContactInput>
}

export type TaxInfoUpdateWithoutContactInput = {
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  company?: Prisma.CompanyUpdateOneWithoutTaxInfoNestedInput
}

export type TaxInfoUncheckedUpdateWithoutContactInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taxNumber?: Prisma.StringFieldUpdateOperationsInput | string
  taxCountry?: Prisma.StringFieldUpdateOperationsInput | string
  isTaxExempt?: Prisma.BoolFieldUpdateOperationsInput | boolean
  exemptionNote?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  companyId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type TaxInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  updatedAt?: boolean
  taxNumber?: boolean
  taxCountry?: boolean
  isTaxExempt?: boolean
  exemptionNote?: boolean
  companyId?: boolean
  contactId?: boolean
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}, ExtArgs["result"]["taxInfo"]>

export type TaxInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  updatedAt?: boolean
  taxNumber?: boolean
  taxCountry?: boolean
  isTaxExempt?: boolean
  exemptionNote?: boolean
  companyId?: boolean
  contactId?: boolean
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}, ExtArgs["result"]["taxInfo"]>

export type TaxInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  updatedAt?: boolean
  taxNumber?: boolean
  taxCountry?: boolean
  isTaxExempt?: boolean
  exemptionNote?: boolean
  companyId?: boolean
  contactId?: boolean
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}, ExtArgs["result"]["taxInfo"]>

export type TaxInfoSelectScalar = {
  id?: boolean
  updatedAt?: boolean
  taxNumber?: boolean
  taxCountry?: boolean
  isTaxExempt?: boolean
  exemptionNote?: boolean
  companyId?: boolean
  contactId?: boolean
}

export type TaxInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "updatedAt" | "taxNumber" | "taxCountry" | "isTaxExempt" | "exemptionNote" | "companyId" | "contactId", ExtArgs["result"]["taxInfo"]>
export type TaxInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}
export type TaxInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}
export type TaxInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.TaxInfo$companyArgs<ExtArgs>
  contact?: boolean | Prisma.TaxInfo$contactArgs<ExtArgs>
}

export type $TaxInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaxInfo"
  objects: {
    company: Prisma.$CompanyPayload<ExtArgs> | null
    contact: Prisma.$ContactPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    updatedAt: Date
    taxNumber: string
    taxCountry: string
    isTaxExempt: boolean
    exemptionNote: string | null
    companyId: number | null
    contactId: number | null
  }, ExtArgs["result"]["taxInfo"]>
  composites: {}
}

export type TaxInfoGetPayload<S extends boolean | null | undefined | TaxInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload, S>

export type TaxInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaxInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaxInfoCountAggregateInputType | true
  }

export interface TaxInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaxInfo'], meta: { name: 'TaxInfo' } }
  /**
   * Find zero or one TaxInfo that matches the filter.
   * @param {TaxInfoFindUniqueArgs} args - Arguments to find a TaxInfo
   * @example
   * // Get one TaxInfo
   * const taxInfo = await prisma.taxInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaxInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, TaxInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaxInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaxInfoFindUniqueOrThrowArgs} args - Arguments to find a TaxInfo
   * @example
   * // Get one TaxInfo
   * const taxInfo = await prisma.taxInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaxInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaxInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoFindFirstArgs} args - Arguments to find a TaxInfo
   * @example
   * // Get one TaxInfo
   * const taxInfo = await prisma.taxInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaxInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, TaxInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaxInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoFindFirstOrThrowArgs} args - Arguments to find a TaxInfo
   * @example
   * // Get one TaxInfo
   * const taxInfo = await prisma.taxInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaxInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaxInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaxInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaxInfos
   * const taxInfos = await prisma.taxInfo.findMany()
   * 
   * // Get first 10 TaxInfos
   * const taxInfos = await prisma.taxInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taxInfoWithIdOnly = await prisma.taxInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaxInfoFindManyArgs>(args?: Prisma.SelectSubset<T, TaxInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaxInfo.
   * @param {TaxInfoCreateArgs} args - Arguments to create a TaxInfo.
   * @example
   * // Create one TaxInfo
   * const TaxInfo = await prisma.taxInfo.create({
   *   data: {
   *     // ... data to create a TaxInfo
   *   }
   * })
   * 
   */
  create<T extends TaxInfoCreateArgs>(args: Prisma.SelectSubset<T, TaxInfoCreateArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaxInfos.
   * @param {TaxInfoCreateManyArgs} args - Arguments to create many TaxInfos.
   * @example
   * // Create many TaxInfos
   * const taxInfo = await prisma.taxInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaxInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, TaxInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaxInfos and returns the data saved in the database.
   * @param {TaxInfoCreateManyAndReturnArgs} args - Arguments to create many TaxInfos.
   * @example
   * // Create many TaxInfos
   * const taxInfo = await prisma.taxInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaxInfos and only return the `id`
   * const taxInfoWithIdOnly = await prisma.taxInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaxInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaxInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaxInfo.
   * @param {TaxInfoDeleteArgs} args - Arguments to delete one TaxInfo.
   * @example
   * // Delete one TaxInfo
   * const TaxInfo = await prisma.taxInfo.delete({
   *   where: {
   *     // ... filter to delete one TaxInfo
   *   }
   * })
   * 
   */
  delete<T extends TaxInfoDeleteArgs>(args: Prisma.SelectSubset<T, TaxInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaxInfo.
   * @param {TaxInfoUpdateArgs} args - Arguments to update one TaxInfo.
   * @example
   * // Update one TaxInfo
   * const taxInfo = await prisma.taxInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaxInfoUpdateArgs>(args: Prisma.SelectSubset<T, TaxInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaxInfos.
   * @param {TaxInfoDeleteManyArgs} args - Arguments to filter TaxInfos to delete.
   * @example
   * // Delete a few TaxInfos
   * const { count } = await prisma.taxInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaxInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaxInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaxInfos
   * const taxInfo = await prisma.taxInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaxInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, TaxInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaxInfos and returns the data updated in the database.
   * @param {TaxInfoUpdateManyAndReturnArgs} args - Arguments to update many TaxInfos.
   * @example
   * // Update many TaxInfos
   * const taxInfo = await prisma.taxInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaxInfos and only return the `id`
   * const taxInfoWithIdOnly = await prisma.taxInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaxInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaxInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaxInfo.
   * @param {TaxInfoUpsertArgs} args - Arguments to update or create a TaxInfo.
   * @example
   * // Update or create a TaxInfo
   * const taxInfo = await prisma.taxInfo.upsert({
   *   create: {
   *     // ... data to create a TaxInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaxInfo we want to update
   *   }
   * })
   */
  upsert<T extends TaxInfoUpsertArgs>(args: Prisma.SelectSubset<T, TaxInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__TaxInfoClient<runtime.Types.Result.GetResult<Prisma.$TaxInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaxInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoCountArgs} args - Arguments to filter TaxInfos to count.
   * @example
   * // Count the number of TaxInfos
   * const count = await prisma.taxInfo.count({
   *   where: {
   *     // ... the filter for the TaxInfos we want to count
   *   }
   * })
  **/
  count<T extends TaxInfoCountArgs>(
    args?: Prisma.Subset<T, TaxInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaxInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaxInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaxInfoAggregateArgs>(args: Prisma.Subset<T, TaxInfoAggregateArgs>): Prisma.PrismaPromise<GetTaxInfoAggregateType<T>>

  /**
   * Group by TaxInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaxInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaxInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaxInfoGroupByArgs['orderBy'] }
      : { orderBy?: TaxInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaxInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaxInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaxInfo model
 */
readonly fields: TaxInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaxInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaxInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  company<T extends Prisma.TaxInfo$companyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaxInfo$companyArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  contact<T extends Prisma.TaxInfo$contactArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaxInfo$contactArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaxInfo model
 */
export interface TaxInfoFieldRefs {
  readonly id: Prisma.FieldRef<"TaxInfo", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"TaxInfo", 'DateTime'>
  readonly taxNumber: Prisma.FieldRef<"TaxInfo", 'String'>
  readonly taxCountry: Prisma.FieldRef<"TaxInfo", 'String'>
  readonly isTaxExempt: Prisma.FieldRef<"TaxInfo", 'Boolean'>
  readonly exemptionNote: Prisma.FieldRef<"TaxInfo", 'String'>
  readonly companyId: Prisma.FieldRef<"TaxInfo", 'Int'>
  readonly contactId: Prisma.FieldRef<"TaxInfo", 'Int'>
}
    

// Custom InputTypes
/**
 * TaxInfo findUnique
 */
export type TaxInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter, which TaxInfo to fetch.
   */
  where: Prisma.TaxInfoWhereUniqueInput
}

/**
 * TaxInfo findUniqueOrThrow
 */
export type TaxInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter, which TaxInfo to fetch.
   */
  where: Prisma.TaxInfoWhereUniqueInput
}

/**
 * TaxInfo findFirst
 */
export type TaxInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter, which TaxInfo to fetch.
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxInfos to fetch.
   */
  orderBy?: Prisma.TaxInfoOrderByWithRelationInput | Prisma.TaxInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxInfos.
   */
  cursor?: Prisma.TaxInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxInfos.
   */
  distinct?: Prisma.TaxInfoScalarFieldEnum | Prisma.TaxInfoScalarFieldEnum[]
}

/**
 * TaxInfo findFirstOrThrow
 */
export type TaxInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter, which TaxInfo to fetch.
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxInfos to fetch.
   */
  orderBy?: Prisma.TaxInfoOrderByWithRelationInput | Prisma.TaxInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaxInfos.
   */
  cursor?: Prisma.TaxInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaxInfos.
   */
  distinct?: Prisma.TaxInfoScalarFieldEnum | Prisma.TaxInfoScalarFieldEnum[]
}

/**
 * TaxInfo findMany
 */
export type TaxInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter, which TaxInfos to fetch.
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaxInfos to fetch.
   */
  orderBy?: Prisma.TaxInfoOrderByWithRelationInput | Prisma.TaxInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaxInfos.
   */
  cursor?: Prisma.TaxInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaxInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaxInfos.
   */
  skip?: number
  distinct?: Prisma.TaxInfoScalarFieldEnum | Prisma.TaxInfoScalarFieldEnum[]
}

/**
 * TaxInfo create
 */
export type TaxInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a TaxInfo.
   */
  data: Prisma.XOR<Prisma.TaxInfoCreateInput, Prisma.TaxInfoUncheckedCreateInput>
}

/**
 * TaxInfo createMany
 */
export type TaxInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaxInfos.
   */
  data: Prisma.TaxInfoCreateManyInput | Prisma.TaxInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaxInfo createManyAndReturn
 */
export type TaxInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * The data used to create many TaxInfos.
   */
  data: Prisma.TaxInfoCreateManyInput | Prisma.TaxInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TaxInfo update
 */
export type TaxInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a TaxInfo.
   */
  data: Prisma.XOR<Prisma.TaxInfoUpdateInput, Prisma.TaxInfoUncheckedUpdateInput>
  /**
   * Choose, which TaxInfo to update.
   */
  where: Prisma.TaxInfoWhereUniqueInput
}

/**
 * TaxInfo updateMany
 */
export type TaxInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaxInfos.
   */
  data: Prisma.XOR<Prisma.TaxInfoUpdateManyMutationInput, Prisma.TaxInfoUncheckedUpdateManyInput>
  /**
   * Filter which TaxInfos to update
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * Limit how many TaxInfos to update.
   */
  limit?: number
}

/**
 * TaxInfo updateManyAndReturn
 */
export type TaxInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * The data used to update TaxInfos.
   */
  data: Prisma.XOR<Prisma.TaxInfoUpdateManyMutationInput, Prisma.TaxInfoUncheckedUpdateManyInput>
  /**
   * Filter which TaxInfos to update
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * Limit how many TaxInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TaxInfo upsert
 */
export type TaxInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the TaxInfo to update in case it exists.
   */
  where: Prisma.TaxInfoWhereUniqueInput
  /**
   * In case the TaxInfo found by the `where` argument doesn't exist, create a new TaxInfo with this data.
   */
  create: Prisma.XOR<Prisma.TaxInfoCreateInput, Prisma.TaxInfoUncheckedCreateInput>
  /**
   * In case the TaxInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaxInfoUpdateInput, Prisma.TaxInfoUncheckedUpdateInput>
}

/**
 * TaxInfo delete
 */
export type TaxInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
  /**
   * Filter which TaxInfo to delete.
   */
  where: Prisma.TaxInfoWhereUniqueInput
}

/**
 * TaxInfo deleteMany
 */
export type TaxInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaxInfos to delete
   */
  where?: Prisma.TaxInfoWhereInput
  /**
   * Limit how many TaxInfos to delete.
   */
  limit?: number
}

/**
 * TaxInfo.company
 */
export type TaxInfo$companyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  where?: Prisma.CompanyWhereInput
}

/**
 * TaxInfo.contact
 */
export type TaxInfo$contactArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  where?: Prisma.ContactWhereInput
}

/**
 * TaxInfo without action
 */
export type TaxInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxInfo
   */
  select?: Prisma.TaxInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxInfo
   */
  omit?: Prisma.TaxInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaxInfoInclude<ExtArgs> | null
}
