
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Email` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Email
 * 
 */
export type EmailModel = runtime.Types.Result.DefaultSelection<Prisma.$EmailPayload>

export type AggregateEmail = {
  _count: EmailCountAggregateOutputType | null
  _avg: EmailAvgAggregateOutputType | null
  _sum: EmailSumAggregateOutputType | null
  _min: EmailMinAggregateOutputType | null
  _max: EmailMaxAggregateOutputType | null
}

export type EmailAvgAggregateOutputType = {
  id: number | null
  contactId: number | null
}

export type EmailSumAggregateOutputType = {
  id: number | null
  contactId: number | null
}

export type EmailMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  contactType: $Enums.PersonalOrWork | null
  email: string | null
  notes: string | null
  contactId: number | null
}

export type EmailMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  contactType: $Enums.PersonalOrWork | null
  email: string | null
  notes: string | null
  contactId: number | null
}

export type EmailCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  contactType: number
  email: number
  notes: number
  contactId: number
  openTime: number
  _all: number
}


export type EmailAvgAggregateInputType = {
  id?: true
  contactId?: true
}

export type EmailSumAggregateInputType = {
  id?: true
  contactId?: true
}

export type EmailMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  contactType?: true
  email?: true
  notes?: true
  contactId?: true
}

export type EmailMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  contactType?: true
  email?: true
  notes?: true
  contactId?: true
}

export type EmailCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  contactType?: true
  email?: true
  notes?: true
  contactId?: true
  openTime?: true
  _all?: true
}

export type EmailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Email to aggregate.
   */
  where?: Prisma.EmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emails to fetch.
   */
  orderBy?: Prisma.EmailOrderByWithRelationInput | Prisma.EmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Emails
  **/
  _count?: true | EmailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmailAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmailSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmailMaxAggregateInputType
}

export type GetEmailAggregateType<T extends EmailAggregateArgs> = {
      [P in keyof T & keyof AggregateEmail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmail[P]>
    : Prisma.GetScalarType<T[P], AggregateEmail[P]>
}




export type EmailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailWhereInput
  orderBy?: Prisma.EmailOrderByWithAggregationInput | Prisma.EmailOrderByWithAggregationInput[]
  by: Prisma.EmailScalarFieldEnum[] | Prisma.EmailScalarFieldEnum
  having?: Prisma.EmailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmailCountAggregateInputType | true
  _avg?: EmailAvgAggregateInputType
  _sum?: EmailSumAggregateInputType
  _min?: EmailMinAggregateInputType
  _max?: EmailMaxAggregateInputType
}

export type EmailGroupByOutputType = {
  id: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  contactType: $Enums.PersonalOrWork
  email: string
  notes: string | null
  contactId: number
  openTime: runtime.JsonValue | null
  _count: EmailCountAggregateOutputType | null
  _avg: EmailAvgAggregateOutputType | null
  _sum: EmailSumAggregateOutputType | null
  _min: EmailMinAggregateOutputType | null
  _max: EmailMaxAggregateOutputType | null
}

type GetEmailGroupByPayload<T extends EmailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmailGroupByOutputType[P]>
      }
    >
  >



export type EmailWhereInput = {
  AND?: Prisma.EmailWhereInput | Prisma.EmailWhereInput[]
  OR?: Prisma.EmailWhereInput[]
  NOT?: Prisma.EmailWhereInput | Prisma.EmailWhereInput[]
  id?: Prisma.IntFilter<"Email"> | number
  createdAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Email"> | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFilter<"Email"> | $Enums.PersonalOrWork
  email?: Prisma.StringFilter<"Email"> | string
  notes?: Prisma.StringNullableFilter<"Email"> | string | null
  contactId?: Prisma.IntFilter<"Email"> | number
  openTime?: Prisma.JsonNullableFilter<"Email">
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
  contacts?: Prisma.ContactListRelationFilter
}

export type EmailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  contactType?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrder
  openTime?: Prisma.SortOrderInput | Prisma.SortOrder
  contact?: Prisma.ContactOrderByWithRelationInput
  contacts?: Prisma.ContactOrderByRelationAggregateInput
}

export type EmailWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  contactId_email?: Prisma.EmailContactIdEmailCompoundUniqueInput
  AND?: Prisma.EmailWhereInput | Prisma.EmailWhereInput[]
  OR?: Prisma.EmailWhereInput[]
  NOT?: Prisma.EmailWhereInput | Prisma.EmailWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Email"> | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFilter<"Email"> | $Enums.PersonalOrWork
  email?: Prisma.StringFilter<"Email"> | string
  notes?: Prisma.StringNullableFilter<"Email"> | string | null
  contactId?: Prisma.IntFilter<"Email"> | number
  openTime?: Prisma.JsonNullableFilter<"Email">
  contact?: Prisma.XOR<Prisma.ContactScalarRelationFilter, Prisma.ContactWhereInput>
  contacts?: Prisma.ContactListRelationFilter
}, "id" | "contactId_email">

export type EmailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  contactType?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  contactId?: Prisma.SortOrder
  openTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EmailCountOrderByAggregateInput
  _avg?: Prisma.EmailAvgOrderByAggregateInput
  _max?: Prisma.EmailMaxOrderByAggregateInput
  _min?: Prisma.EmailMinOrderByAggregateInput
  _sum?: Prisma.EmailSumOrderByAggregateInput
}

export type EmailScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmailScalarWhereWithAggregatesInput | Prisma.EmailScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmailScalarWhereWithAggregatesInput | Prisma.EmailScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Email"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Email"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Email"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Email"> | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkWithAggregatesFilter<"Email"> | $Enums.PersonalOrWork
  email?: Prisma.StringWithAggregatesFilter<"Email"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"Email"> | string | null
  contactId?: Prisma.IntWithAggregatesFilter<"Email"> | number
  openTime?: Prisma.JsonNullableWithAggregatesFilter<"Email">
}

export type EmailCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contact: Prisma.ContactCreateNestedOneWithoutEmailsInput
  contacts?: Prisma.ContactCreateNestedManyWithoutPrimaryEmailInput
}

export type EmailUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  contactId: number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedCreateNestedManyWithoutPrimaryEmailInput
}

export type EmailUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contact?: Prisma.ContactUpdateOneRequiredWithoutEmailsNestedInput
  contacts?: Prisma.ContactUpdateManyWithoutPrimaryEmailNestedInput
}

export type EmailUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedUpdateManyWithoutPrimaryEmailNestedInput
}

export type EmailCreateManyInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  contactId: number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailNullableScalarRelationFilter = {
  is?: Prisma.EmailWhereInput | null
  isNot?: Prisma.EmailWhereInput | null
}

export type EmailListRelationFilter = {
  every?: Prisma.EmailWhereInput
  some?: Prisma.EmailWhereInput
  none?: Prisma.EmailWhereInput
}

export type EmailOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmailContactIdEmailCompoundUniqueInput = {
  contactId: number
  email: string
}

export type EmailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  contactType?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
}

export type EmailAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type EmailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  contactType?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type EmailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  contactType?: Prisma.SortOrder
  email?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type EmailSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
}

export type EmailCreateNestedOneWithoutContactsInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactsInput, Prisma.EmailUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactsInput
  connect?: Prisma.EmailWhereUniqueInput
}

export type EmailCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput> | Prisma.EmailCreateWithoutContactInput[] | Prisma.EmailUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactInput | Prisma.EmailCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.EmailCreateManyContactInputEnvelope
  connect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
}

export type EmailUncheckedCreateNestedManyWithoutContactInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput> | Prisma.EmailCreateWithoutContactInput[] | Prisma.EmailUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactInput | Prisma.EmailCreateOrConnectWithoutContactInput[]
  createMany?: Prisma.EmailCreateManyContactInputEnvelope
  connect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
}

export type EmailUpdateOneWithoutContactsNestedInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactsInput, Prisma.EmailUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactsInput
  upsert?: Prisma.EmailUpsertWithoutContactsInput
  disconnect?: Prisma.EmailWhereInput | boolean
  delete?: Prisma.EmailWhereInput | boolean
  connect?: Prisma.EmailWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmailUpdateToOneWithWhereWithoutContactsInput, Prisma.EmailUpdateWithoutContactsInput>, Prisma.EmailUncheckedUpdateWithoutContactsInput>
}

export type EmailUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput> | Prisma.EmailCreateWithoutContactInput[] | Prisma.EmailUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactInput | Prisma.EmailCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.EmailUpsertWithWhereUniqueWithoutContactInput | Prisma.EmailUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.EmailCreateManyContactInputEnvelope
  set?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  disconnect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  delete?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  connect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  update?: Prisma.EmailUpdateWithWhereUniqueWithoutContactInput | Prisma.EmailUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.EmailUpdateManyWithWhereWithoutContactInput | Prisma.EmailUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.EmailScalarWhereInput | Prisma.EmailScalarWhereInput[]
}

export type EmailUncheckedUpdateManyWithoutContactNestedInput = {
  create?: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput> | Prisma.EmailCreateWithoutContactInput[] | Prisma.EmailUncheckedCreateWithoutContactInput[]
  connectOrCreate?: Prisma.EmailCreateOrConnectWithoutContactInput | Prisma.EmailCreateOrConnectWithoutContactInput[]
  upsert?: Prisma.EmailUpsertWithWhereUniqueWithoutContactInput | Prisma.EmailUpsertWithWhereUniqueWithoutContactInput[]
  createMany?: Prisma.EmailCreateManyContactInputEnvelope
  set?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  disconnect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  delete?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  connect?: Prisma.EmailWhereUniqueInput | Prisma.EmailWhereUniqueInput[]
  update?: Prisma.EmailUpdateWithWhereUniqueWithoutContactInput | Prisma.EmailUpdateWithWhereUniqueWithoutContactInput[]
  updateMany?: Prisma.EmailUpdateManyWithWhereWithoutContactInput | Prisma.EmailUpdateManyWithWhereWithoutContactInput[]
  deleteMany?: Prisma.EmailScalarWhereInput | Prisma.EmailScalarWhereInput[]
}

export type EnumPersonalOrWorkFieldUpdateOperationsInput = {
  set?: $Enums.PersonalOrWork
}

export type EmailCreateWithoutContactsInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contact: Prisma.ContactCreateNestedOneWithoutEmailsInput
}

export type EmailUncheckedCreateWithoutContactsInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  contactId: number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailCreateOrConnectWithoutContactsInput = {
  where: Prisma.EmailWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailCreateWithoutContactsInput, Prisma.EmailUncheckedCreateWithoutContactsInput>
}

export type EmailCreateWithoutContactInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactCreateNestedManyWithoutPrimaryEmailInput
}

export type EmailUncheckedCreateWithoutContactInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedCreateNestedManyWithoutPrimaryEmailInput
}

export type EmailCreateOrConnectWithoutContactInput = {
  where: Prisma.EmailWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput>
}

export type EmailCreateManyContactInputEnvelope = {
  data: Prisma.EmailCreateManyContactInput | Prisma.EmailCreateManyContactInput[]
  skipDuplicates?: boolean
}

export type EmailUpsertWithoutContactsInput = {
  update: Prisma.XOR<Prisma.EmailUpdateWithoutContactsInput, Prisma.EmailUncheckedUpdateWithoutContactsInput>
  create: Prisma.XOR<Prisma.EmailCreateWithoutContactsInput, Prisma.EmailUncheckedCreateWithoutContactsInput>
  where?: Prisma.EmailWhereInput
}

export type EmailUpdateToOneWithWhereWithoutContactsInput = {
  where?: Prisma.EmailWhereInput
  data: Prisma.XOR<Prisma.EmailUpdateWithoutContactsInput, Prisma.EmailUncheckedUpdateWithoutContactsInput>
}

export type EmailUpdateWithoutContactsInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contact?: Prisma.ContactUpdateOneRequiredWithoutEmailsNestedInput
}

export type EmailUncheckedUpdateWithoutContactsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactId?: Prisma.IntFieldUpdateOperationsInput | number
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailUpsertWithWhereUniqueWithoutContactInput = {
  where: Prisma.EmailWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailUpdateWithoutContactInput, Prisma.EmailUncheckedUpdateWithoutContactInput>
  create: Prisma.XOR<Prisma.EmailCreateWithoutContactInput, Prisma.EmailUncheckedCreateWithoutContactInput>
}

export type EmailUpdateWithWhereUniqueWithoutContactInput = {
  where: Prisma.EmailWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailUpdateWithoutContactInput, Prisma.EmailUncheckedUpdateWithoutContactInput>
}

export type EmailUpdateManyWithWhereWithoutContactInput = {
  where: Prisma.EmailScalarWhereInput
  data: Prisma.XOR<Prisma.EmailUpdateManyMutationInput, Prisma.EmailUncheckedUpdateManyWithoutContactInput>
}

export type EmailScalarWhereInput = {
  AND?: Prisma.EmailScalarWhereInput | Prisma.EmailScalarWhereInput[]
  OR?: Prisma.EmailScalarWhereInput[]
  NOT?: Prisma.EmailScalarWhereInput | Prisma.EmailScalarWhereInput[]
  id?: Prisma.IntFilter<"Email"> | number
  createdAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Email"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Email"> | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFilter<"Email"> | $Enums.PersonalOrWork
  email?: Prisma.StringFilter<"Email"> | string
  notes?: Prisma.StringNullableFilter<"Email"> | string | null
  contactId?: Prisma.IntFilter<"Email"> | number
  openTime?: Prisma.JsonNullableFilter<"Email">
}

export type EmailCreateManyContactInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  contactType?: $Enums.PersonalOrWork
  email: string
  notes?: string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type EmailUpdateWithoutContactInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUpdateManyWithoutPrimaryEmailNestedInput
}

export type EmailUncheckedUpdateWithoutContactInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  contacts?: Prisma.ContactUncheckedUpdateManyWithoutPrimaryEmailNestedInput
}

export type EmailUncheckedUpdateManyWithoutContactInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactType?: Prisma.EnumPersonalOrWorkFieldUpdateOperationsInput | $Enums.PersonalOrWork
  email?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  openTime?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type EmailCountOutputType
 */

export type EmailCountOutputType = {
  contacts: number
}

export type EmailCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contacts?: boolean | EmailCountOutputTypeCountContactsArgs
}

/**
 * EmailCountOutputType without action
 */
export type EmailCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailCountOutputType
   */
  select?: Prisma.EmailCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmailCountOutputType without action
 */
export type EmailCountOutputTypeCountContactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContactWhereInput
}


export type EmailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  contactType?: boolean
  email?: boolean
  notes?: boolean
  contactId?: boolean
  openTime?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  contacts?: boolean | Prisma.Email$contactsArgs<ExtArgs>
  _count?: boolean | Prisma.EmailCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email"]>

export type EmailSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  contactType?: boolean
  email?: boolean
  notes?: boolean
  contactId?: boolean
  openTime?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email"]>

export type EmailSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  contactType?: boolean
  email?: boolean
  notes?: boolean
  contactId?: boolean
  openTime?: boolean
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email"]>

export type EmailSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  contactType?: boolean
  email?: boolean
  notes?: boolean
  contactId?: boolean
  openTime?: boolean
}

export type EmailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "deletedAt" | "contactType" | "email" | "notes" | "contactId" | "openTime", ExtArgs["result"]["email"]>
export type EmailInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
  contacts?: boolean | Prisma.Email$contactsArgs<ExtArgs>
  _count?: boolean | Prisma.EmailCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmailIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}
export type EmailIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contact?: boolean | Prisma.ContactDefaultArgs<ExtArgs>
}

export type $EmailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Email"
  objects: {
    contact: Prisma.$ContactPayload<ExtArgs>
    contacts: Prisma.$ContactPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    contactType: $Enums.PersonalOrWork
    email: string
    notes: string | null
    contactId: number
    openTime: runtime.JsonValue | null
  }, ExtArgs["result"]["email"]>
  composites: {}
}

export type EmailGetPayload<S extends boolean | null | undefined | EmailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmailPayload, S>

export type EmailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmailCountAggregateInputType | true
  }

export interface EmailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Email'], meta: { name: 'Email' } }
  /**
   * Find zero or one Email that matches the filter.
   * @param {EmailFindUniqueArgs} args - Arguments to find a Email
   * @example
   * // Get one Email
   * const email = await prisma.email.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmailFindUniqueArgs>(args: Prisma.SelectSubset<T, EmailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Email that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmailFindUniqueOrThrowArgs} args - Arguments to find a Email
   * @example
   * // Get one Email
   * const email = await prisma.email.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Email that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailFindFirstArgs} args - Arguments to find a Email
   * @example
   * // Get one Email
   * const email = await prisma.email.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmailFindFirstArgs>(args?: Prisma.SelectSubset<T, EmailFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Email that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailFindFirstOrThrowArgs} args - Arguments to find a Email
   * @example
   * // Get one Email
   * const email = await prisma.email.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Emails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Emails
   * const emails = await prisma.email.findMany()
   * 
   * // Get first 10 Emails
   * const emails = await prisma.email.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emailWithIdOnly = await prisma.email.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmailFindManyArgs>(args?: Prisma.SelectSubset<T, EmailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Email.
   * @param {EmailCreateArgs} args - Arguments to create a Email.
   * @example
   * // Create one Email
   * const Email = await prisma.email.create({
   *   data: {
   *     // ... data to create a Email
   *   }
   * })
   * 
   */
  create<T extends EmailCreateArgs>(args: Prisma.SelectSubset<T, EmailCreateArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Emails.
   * @param {EmailCreateManyArgs} args - Arguments to create many Emails.
   * @example
   * // Create many Emails
   * const email = await prisma.email.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmailCreateManyArgs>(args?: Prisma.SelectSubset<T, EmailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Emails and returns the data saved in the database.
   * @param {EmailCreateManyAndReturnArgs} args - Arguments to create many Emails.
   * @example
   * // Create many Emails
   * const email = await prisma.email.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Emails and only return the `id`
   * const emailWithIdOnly = await prisma.email.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmailCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmailCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Email.
   * @param {EmailDeleteArgs} args - Arguments to delete one Email.
   * @example
   * // Delete one Email
   * const Email = await prisma.email.delete({
   *   where: {
   *     // ... filter to delete one Email
   *   }
   * })
   * 
   */
  delete<T extends EmailDeleteArgs>(args: Prisma.SelectSubset<T, EmailDeleteArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Email.
   * @param {EmailUpdateArgs} args - Arguments to update one Email.
   * @example
   * // Update one Email
   * const email = await prisma.email.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmailUpdateArgs>(args: Prisma.SelectSubset<T, EmailUpdateArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Emails.
   * @param {EmailDeleteManyArgs} args - Arguments to filter Emails to delete.
   * @example
   * // Delete a few Emails
   * const { count } = await prisma.email.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmailDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Emails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Emails
   * const email = await prisma.email.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmailUpdateManyArgs>(args: Prisma.SelectSubset<T, EmailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Emails and returns the data updated in the database.
   * @param {EmailUpdateManyAndReturnArgs} args - Arguments to update many Emails.
   * @example
   * // Update many Emails
   * const email = await prisma.email.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Emails and only return the `id`
   * const emailWithIdOnly = await prisma.email.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmailUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmailUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Email.
   * @param {EmailUpsertArgs} args - Arguments to update or create a Email.
   * @example
   * // Update or create a Email
   * const email = await prisma.email.upsert({
   *   create: {
   *     // ... data to create a Email
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Email we want to update
   *   }
   * })
   */
  upsert<T extends EmailUpsertArgs>(args: Prisma.SelectSubset<T, EmailUpsertArgs<ExtArgs>>): Prisma.Prisma__EmailClient<runtime.Types.Result.GetResult<Prisma.$EmailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Emails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailCountArgs} args - Arguments to filter Emails to count.
   * @example
   * // Count the number of Emails
   * const count = await prisma.email.count({
   *   where: {
   *     // ... the filter for the Emails we want to count
   *   }
   * })
  **/
  count<T extends EmailCountArgs>(
    args?: Prisma.Subset<T, EmailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Email.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmailAggregateArgs>(args: Prisma.Subset<T, EmailAggregateArgs>): Prisma.PrismaPromise<GetEmailAggregateType<T>>

  /**
   * Group by Email.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmailGroupByArgs['orderBy'] }
      : { orderBy?: EmailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Email model
 */
readonly fields: EmailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Email.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contact<T extends Prisma.ContactDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContactDefaultArgs<ExtArgs>>): Prisma.Prisma__ContactClient<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contacts<T extends Prisma.Email$contactsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Email$contactsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Email model
 */
export interface EmailFieldRefs {
  readonly id: Prisma.FieldRef<"Email", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Email", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Email", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Email", 'DateTime'>
  readonly contactType: Prisma.FieldRef<"Email", 'PersonalOrWork'>
  readonly email: Prisma.FieldRef<"Email", 'String'>
  readonly notes: Prisma.FieldRef<"Email", 'String'>
  readonly contactId: Prisma.FieldRef<"Email", 'Int'>
  readonly openTime: Prisma.FieldRef<"Email", 'Json'>
}
    

// Custom InputTypes
/**
 * Email findUnique
 */
export type EmailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter, which Email to fetch.
   */
  where: Prisma.EmailWhereUniqueInput
}

/**
 * Email findUniqueOrThrow
 */
export type EmailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter, which Email to fetch.
   */
  where: Prisma.EmailWhereUniqueInput
}

/**
 * Email findFirst
 */
export type EmailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter, which Email to fetch.
   */
  where?: Prisma.EmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emails to fetch.
   */
  orderBy?: Prisma.EmailOrderByWithRelationInput | Prisma.EmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Emails.
   */
  cursor?: Prisma.EmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Emails.
   */
  distinct?: Prisma.EmailScalarFieldEnum | Prisma.EmailScalarFieldEnum[]
}

/**
 * Email findFirstOrThrow
 */
export type EmailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter, which Email to fetch.
   */
  where?: Prisma.EmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emails to fetch.
   */
  orderBy?: Prisma.EmailOrderByWithRelationInput | Prisma.EmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Emails.
   */
  cursor?: Prisma.EmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Emails.
   */
  distinct?: Prisma.EmailScalarFieldEnum | Prisma.EmailScalarFieldEnum[]
}

/**
 * Email findMany
 */
export type EmailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter, which Emails to fetch.
   */
  where?: Prisma.EmailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Emails to fetch.
   */
  orderBy?: Prisma.EmailOrderByWithRelationInput | Prisma.EmailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Emails.
   */
  cursor?: Prisma.EmailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Emails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Emails.
   */
  skip?: number
  distinct?: Prisma.EmailScalarFieldEnum | Prisma.EmailScalarFieldEnum[]
}

/**
 * Email create
 */
export type EmailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * The data needed to create a Email.
   */
  data: Prisma.XOR<Prisma.EmailCreateInput, Prisma.EmailUncheckedCreateInput>
}

/**
 * Email createMany
 */
export type EmailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Emails.
   */
  data: Prisma.EmailCreateManyInput | Prisma.EmailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Email createManyAndReturn
 */
export type EmailCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * The data used to create many Emails.
   */
  data: Prisma.EmailCreateManyInput | Prisma.EmailCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Email update
 */
export type EmailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * The data needed to update a Email.
   */
  data: Prisma.XOR<Prisma.EmailUpdateInput, Prisma.EmailUncheckedUpdateInput>
  /**
   * Choose, which Email to update.
   */
  where: Prisma.EmailWhereUniqueInput
}

/**
 * Email updateMany
 */
export type EmailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Emails.
   */
  data: Prisma.XOR<Prisma.EmailUpdateManyMutationInput, Prisma.EmailUncheckedUpdateManyInput>
  /**
   * Filter which Emails to update
   */
  where?: Prisma.EmailWhereInput
  /**
   * Limit how many Emails to update.
   */
  limit?: number
}

/**
 * Email updateManyAndReturn
 */
export type EmailUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * The data used to update Emails.
   */
  data: Prisma.XOR<Prisma.EmailUpdateManyMutationInput, Prisma.EmailUncheckedUpdateManyInput>
  /**
   * Filter which Emails to update
   */
  where?: Prisma.EmailWhereInput
  /**
   * Limit how many Emails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Email upsert
 */
export type EmailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * The filter to search for the Email to update in case it exists.
   */
  where: Prisma.EmailWhereUniqueInput
  /**
   * In case the Email found by the `where` argument doesn't exist, create a new Email with this data.
   */
  create: Prisma.XOR<Prisma.EmailCreateInput, Prisma.EmailUncheckedCreateInput>
  /**
   * In case the Email was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmailUpdateInput, Prisma.EmailUncheckedUpdateInput>
}

/**
 * Email delete
 */
export type EmailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
  /**
   * Filter which Email to delete.
   */
  where: Prisma.EmailWhereUniqueInput
}

/**
 * Email deleteMany
 */
export type EmailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Emails to delete
   */
  where?: Prisma.EmailWhereInput
  /**
   * Limit how many Emails to delete.
   */
  limit?: number
}

/**
 * Email.contacts
 */
export type Email$contactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contact
   */
  select?: Prisma.ContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contact
   */
  omit?: Prisma.ContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactInclude<ExtArgs> | null
  where?: Prisma.ContactWhereInput
  orderBy?: Prisma.ContactOrderByWithRelationInput | Prisma.ContactOrderByWithRelationInput[]
  cursor?: Prisma.ContactWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ContactScalarFieldEnum | Prisma.ContactScalarFieldEnum[]
}

/**
 * Email without action
 */
export type EmailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Email
   */
  select?: Prisma.EmailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Email
   */
  omit?: Prisma.EmailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailInclude<ExtArgs> | null
}
