export enum Meta {
    PUBLIC = 'PUBLIC_METADATA',
    RESOURCE_NAME = 'RESOURCE_NAME_METADATA',
    OPERATION_NAME = 'OPERATION_NAME_METADATA',
    EMIT = 'EMIT_METADATA',
    ID_PROJECTION = 'ID_PROJECTION_METADATA',
}
