export type * from './commonInputTypes.js';
export type * from './models/Address.js';
export type * from './models/ClockIn.js';
export type * from './models/Contact.js';
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Department.js';
export type * from './models/Email.js';
export type * from './models/Employee.js';
export type * from './models/Occupation.js';
export type * from './models/Phone.js';
