name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.3.0
          run_install: false

      - name: Configure cache
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build projects

      - name: Lint and Generate
        run: |
          pnpm nx run-many -t lint
          pnpm nx run-many -t prisma:generate

      - name: build
        run: pnpm run-many -t build

      - name: Fix ci
        run: pnpm nx fix-ci
        if: always()
